/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pages;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.CompletedOrderUserComplain;
import model.CurrentOrderUserComplain;
import projects.InsertUpdateDelete;
import projects.Select;
import java.sql.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author yangshuya
 */
public class CurrentOrderCustomer extends javax.swing.JFrame {

    /**
     * Creates new form CurrentOrderCustomer
     */
    public CurrentOrderCustomer() {
        initComponents();
        Table();
        Table1();
      
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public void Table(){
         
         
         //String marketname=Login.jTextField1.getText();
                       
           
       ResultSet rs=Select.getData("select * from CustomerService where decision is null and status!='Completed' ");
        DefaultTableModel model=(DefaultTableModel)jTable4.getModel();
        model.setRowCount(0);
        try {
            while(rs.next())
            {
                model.addRow(new Object[]{rs.getInt(2),rs.getString(3),rs.getFloat(6),rs.getString(7)});
            }
            rs.close();
                
            
        } catch (Exception e)
        {
            JOptionPane.showConfirmDialog(null, e);
        }
    }
        
        
        //String deliveryname=Login.jTextField1.getText();
        //jTable5.repaint();
    public void Table1(){
        
        ResultSet rs1=Select.getData("select * from CustomerService where decision is not null and status!='Completed' ");
        DefaultTableModel model2=(DefaultTableModel)jTable5.getModel();
        model2.setRowCount(0);
        try {
            while(rs1.next())
            {
                model2.addRow(new Object[]{rs1.getInt(2),rs1.getString(3),rs1.getFloat(6),rs1.getString(7),rs1.getString(8)});
            }
            rs1.close();
                
            
        } catch (Exception e)
        {
            JOptionPane.showConfirmDialog(null, e);
        }
        jTable5.repaint();
    
    }
    
    public void valueChaged(ListSelectionEvent event){
        if(event.getValueIsAdjusting())
            return;
        if(!jTable5.getSelectionModel().isSelectionEmpty())
            jTable4.getSelectionModel().clearSelection();
    }
   
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        CurrentOrderCSJPanel = new javax.swing.JPanel();
        lblServiceInProgress2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        lblServiceInProgress3 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        btnview1 = new javax.swing.JButton();
        btnback1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        CurrentOrderComplainsJPanel = new javax.swing.JPanel();
        lblComplain = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        lblOrderNumber = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        lblOrderType = new javax.swing.JLabel();
        lblOrderDate = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        lblMarket = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        lblProblem = new javax.swing.JLabel();
        cmbProblem = new javax.swing.JComboBox<>();
        lblTotalAmount = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        lblDetail = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnSubmit = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblDecision = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new java.awt.CardLayout());

        CurrentOrderCSJPanel.setLayout(null);

        lblServiceInProgress2.setFont(new java.awt.Font("Kokonor", 3, 24)); // NOI18N
        lblServiceInProgress2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblServiceInProgress2.setText("In Progress");
        CurrentOrderCSJPanel.add(lblServiceInProgress2);
        lblServiceInProgress2.setBounds(0, 6, 800, 42);

        jTable4.setBackground(new java.awt.Color(204, 255, 204));
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Order Number", "Order Type", "Total Amount", "Problem"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable4);

        CurrentOrderCSJPanel.add(jScrollPane4);
        jScrollPane4.setBounds(6, 66, 788, 169);

        lblServiceInProgress3.setFont(new java.awt.Font("Kokonor", 3, 24)); // NOI18N
        lblServiceInProgress3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblServiceInProgress3.setText("Finished");
        CurrentOrderCSJPanel.add(lblServiceInProgress3);
        lblServiceInProgress3.setBounds(6, 253, 788, 42);

        jTable5.setBackground(new java.awt.Color(204, 255, 204));
        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Order Number", "Order Type", "Total Amount", "Problem", "Decision"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable5.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTable5ComponentShown(evt);
            }
        });
        jScrollPane5.setViewportView(jTable5);

        CurrentOrderCSJPanel.add(jScrollPane5);
        jScrollPane5.setBounds(6, 313, 788, 169);

        btnview1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnview1.setForeground(new java.awt.Color(51, 204, 0));
        btnview1.setText("Back");
        btnview1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnview1ActionPerformed(evt);
            }
        });
        CurrentOrderCSJPanel.add(btnview1);
        btnview1.setBounds(670, 540, 80, 30);

        btnback1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnback1.setForeground(new java.awt.Color(51, 204, 0));
        btnback1.setText("View");
        btnback1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnback1ActionPerformed(evt);
            }
        });
        CurrentOrderCSJPanel.add(btnback1);
        btnback1.setBounds(670, 500, 80, 30);

        jButton4.setBackground(new java.awt.Color(204, 255, 204));
        jButton4.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 51, 0));
        jButton4.setText("Refresh");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        CurrentOrderCSJPanel.add(jButton4);
        jButton4.setBounds(20, 550, 110, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/picture/1-1024x1024.jpeg"))); // NOI18N
        CurrentOrderCSJPanel.add(jLabel2);
        jLabel2.setBounds(-5, -3, 810, 610);

        jPanel2.add(CurrentOrderCSJPanel, "card9");

        CurrentOrderComplainsJPanel.setLayout(null);

        lblComplain.setFont(new java.awt.Font("Kokonor", 3, 24)); // NOI18N
        lblComplain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblComplain.setText("User Complain");
        CurrentOrderComplainsJPanel.add(lblComplain);
        lblComplain.setBounds(130, 20, 520, 42);

        lblUser.setBackground(new java.awt.Color(204, 255, 204));
        lblUser.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblUser.setForeground(new java.awt.Color(0, 102, 0));
        lblUser.setText("User:");
        CurrentOrderComplainsJPanel.add(lblUser);
        lblUser.setBounds(120, 90, 87, 23);
        CurrentOrderComplainsJPanel.add(jTextField1);
        jTextField1.setBounds(190, 90, 115, 30);

        lblOrderNumber.setBackground(new java.awt.Color(204, 255, 204));
        lblOrderNumber.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblOrderNumber.setForeground(new java.awt.Color(0, 102, 0));
        lblOrderNumber.setText("Order Number:");
        CurrentOrderComplainsJPanel.add(lblOrderNumber);
        lblOrderNumber.setBounds(430, 80, 127, 23);
        CurrentOrderComplainsJPanel.add(jTextField2);
        jTextField2.setBounds(590, 80, 115, 30);

        lblOrderType.setBackground(new java.awt.Color(204, 255, 204));
        lblOrderType.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblOrderType.setForeground(new java.awt.Color(0, 102, 0));
        lblOrderType.setText("Order Type:");
        CurrentOrderComplainsJPanel.add(lblOrderType);
        lblOrderType.setBounds(70, 160, 160, 23);

        lblOrderDate.setBackground(new java.awt.Color(204, 255, 204));
        lblOrderDate.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblOrderDate.setForeground(new java.awt.Color(0, 102, 0));
        lblOrderDate.setText("Order Date:");
        CurrentOrderComplainsJPanel.add(lblOrderDate);
        lblOrderDate.setBounds(460, 160, 150, 23);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        CurrentOrderComplainsJPanel.add(jTextField4);
        jTextField4.setBounds(590, 160, 200, 30);

        jComboBox2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Delivery", "Pick-up" }));
        CurrentOrderComplainsJPanel.add(jComboBox2);
        jComboBox2.setBounds(190, 160, 130, 29);

        lblMarket.setBackground(new java.awt.Color(204, 255, 204));
        lblMarket.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblMarket.setForeground(new java.awt.Color(0, 102, 0));
        lblMarket.setText("Market:");
        CurrentOrderComplainsJPanel.add(lblMarket);
        lblMarket.setBounds(100, 240, 110, 23);
        CurrentOrderComplainsJPanel.add(jTextField5);
        jTextField5.setBounds(190, 240, 115, 30);

        lblProblem.setBackground(new java.awt.Color(204, 255, 204));
        lblProblem.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblProblem.setForeground(new java.awt.Color(0, 102, 0));
        lblProblem.setText("Problem:");
        CurrentOrderComplainsJPanel.add(lblProblem);
        lblProblem.setBounds(480, 310, 110, 23);

        cmbProblem.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        cmbProblem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Wrong Order", "Not Received", "Delayed", "Missing Item" }));
        CurrentOrderComplainsJPanel.add(cmbProblem);
        cmbProblem.setBounds(590, 310, 140, 30);

        lblTotalAmount.setBackground(new java.awt.Color(204, 255, 204));
        lblTotalAmount.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblTotalAmount.setForeground(new java.awt.Color(0, 102, 0));
        lblTotalAmount.setText("Total Amount:");
        CurrentOrderComplainsJPanel.add(lblTotalAmount);
        lblTotalAmount.setBounds(50, 320, 170, 23);
        CurrentOrderComplainsJPanel.add(jTextField6);
        jTextField6.setBounds(190, 320, 115, 30);

        lblDetail.setBackground(new java.awt.Color(204, 255, 204));
        lblDetail.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblDetail.setForeground(new java.awt.Color(0, 102, 0));
        lblDetail.setText("Details:");
        CurrentOrderComplainsJPanel.add(lblDetail);
        lblDetail.setBounds(100, 400, 87, 23);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        CurrentOrderComplainsJPanel.add(jScrollPane1);
        jScrollPane1.setBounds(190, 400, 234, 91);

        btnSubmit.setBackground(new java.awt.Color(204, 255, 204));
        btnSubmit.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(102, 153, 0));
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        CurrentOrderComplainsJPanel.add(btnSubmit);
        btnSubmit.setBounds(440, 610, 120, 29);

        btnBack.setBackground(new java.awt.Color(204, 255, 204));
        btnBack.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(102, 153, 0));
        btnBack.setText("Back");
        CurrentOrderComplainsJPanel.add(btnBack);
        btnBack.setBounds(590, 610, 120, 29);

        lblDecision.setBackground(new java.awt.Color(204, 255, 204));
        lblDecision.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblDecision.setForeground(new java.awt.Color(0, 102, 0));
        lblDecision.setText("Decision:");
        CurrentOrderComplainsJPanel.add(lblDecision);
        lblDecision.setBounds(470, 390, 130, 23);

        jComboBox1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "10% Refund", "50% Refund", "75% Refund", "100% Refund" }));
        CurrentOrderComplainsJPanel.add(jComboBox1);
        jComboBox1.setBounds(590, 390, 126, 30);

        jButton1.setBackground(new java.awt.Color(204, 255, 204));
        jButton1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 0));
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        CurrentOrderComplainsJPanel.add(jButton1);
        jButton1.setBounds(600, 470, 120, 30);

        jButton2.setBackground(new java.awt.Color(204, 255, 204));
        jButton2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 51, 51));
        jButton2.setText("Goback");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        CurrentOrderComplainsJPanel.add(jButton2);
        jButton2.setBounds(660, 20, 100, 30);

        jButton3.setBackground(new java.awt.Color(204, 255, 204));
        jButton3.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 51, 51));
        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        CurrentOrderComplainsJPanel.add(jButton3);
        jButton3.setBounds(600, 530, 120, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/picture/1-1024x1024.jpeg"))); // NOI18N
        CurrentOrderComplainsJPanel.add(jLabel4);
        jLabel4.setBounds(0, -3, 800, 700);

        jPanel2.add(CurrentOrderComplainsJPanel, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 794, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 794, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 612, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable5ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTable5ComponentShown
        // TODO add your handling code here:

        ResultSet rs1=Select.getData("select * from CustomerService where decision!='' ");
        DefaultTableModel model2=(DefaultTableModel)jTable5.getModel();
        model2.setRowCount(0);
        try {
            while(rs1.next())
            {
                model2.addRow(new Object[]{rs1.getInt(2),rs1.getString(3),rs1.getFloat(6),rs1.getString(7),rs1.getString(8)});
            }
            rs1.close();

        } catch (Exception e)
        {
            JOptionPane.showConfirmDialog(null, e);
        }
    }//GEN-LAST:event_jTable5ComponentShown

    private void btnview1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnview1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Login().setVisible(true);
        

    }//GEN-LAST:event_btnview1ActionPerformed

    private void btnback1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnback1ActionPerformed
        // TODO add your handling code here:
        CurrentOrderCSJPanel.setVisible(false);
        CurrentOrderComplainsJPanel.setVisible(true);

        int SelectedRowIndex = jTable4.getSelectedRow();
        int SelectedRowIndex2 = jTable5.getSelectedRow();
        
        if (SelectedRowIndex < 0 & SelectedRowIndex2 < 0)
        {
            
            JOptionPane.showMessageDialog(this, "Please Select a Row to View.");
            return;
        }
        else if (SelectedRowIndex >= 0)
          {
 
              DefaultTableModel model = (DefaultTableModel) jTable4.getModel();
              int ordernumber=(int)model.getValueAt(SelectedRowIndex,0);
        
              try 
                   {
           ResultSet rs=Select.getData("select * from CustomerService where ordernumber='"+ordernumber+"' ");
           while(rs.next())
            {
                jTextField1.setText(rs.getString(1));
                jTextField1.setEditable(false);

                jTextField2.setText(String.valueOf(rs.getInt(2)));
                jTextField2.setEditable(false);

                jComboBox2.setSelectedItem(rs.getString(3));
                jComboBox2.setEditable(false);

                jTextField4.setText(rs.getString(4));
                jTextField4.setEditable(false);

                jTextField5.setText(rs.getString(5));
                jTextField5.setEditable(false);

                cmbProblem.setSelectedItem(rs.getString(7));
                cmbProblem.setEnabled(false);

                jTextField6.setText(String.valueOf(rs.getFloat(6)));
                jTextField6.setEditable(false);

                jTextArea1.setText(rs.getString(10));
                jTextArea1.setEditable(false);

                jComboBox1.setSelectedIndex(0);
                jComboBox1.setEnabled(true);

                jButton1.setEnabled(true);
                jButton3.setEnabled(false);
            }rs.close();
  
        } catch (Exception e)
        {
            JOptionPane.showConfirmDialog(null, e);
            
        }
    }
  
        else if(SelectedRowIndex2 >= 0)
        {
            DefaultTableModel model = (DefaultTableModel) jTable5.getModel();
            int ordernumber=(int)model.getValueAt(SelectedRowIndex2,0);
            ResultSet rs=Select.getData("select * from CustomerService where ordernumber='"+ordernumber+"' ");
            try{
                while(rs.next())
                {
                jTextField1.setText((rs.getString(1)));
                jTextField1.setEditable(false);

                jTextField2.setText(String.valueOf(rs.getInt(2)));
                jTextField2.setEditable(false);

                jComboBox2.setSelectedItem(rs.getString(3));
                jComboBox2.setEditable(false);

                jTextField4.setText(rs.getString(4));
                jTextField4.setEditable(false);

                jTextField5.setText(rs.getString(5));
                jTextField5.setEditable(false);

                cmbProblem.setSelectedItem(rs.getString(7));
                cmbProblem.setEnabled(false);

                jTextField6.setText(String.valueOf(rs.getFloat(6)));
                jTextField6.setEditable(false);

                jTextArea1.setText(rs.getString(10));
                jTextArea1.setEditable(false);

                jComboBox1.setSelectedItem(rs.getString(8));
                jComboBox1.setEnabled(true);

                jButton1.setEnabled(false);
                jButton3.setEnabled(true);
                }rs.close();
            }
            catch (Exception e)
            {
                JOptionPane.showConfirmDialog(null, e);
            }
        }
    

          
    }//GEN-LAST:event_btnback1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnSubmitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int ordernum=Integer.parseInt(jTextField2.getText());
        String decision=(String)jComboBox1.getSelectedItem();

        try
        {
            String Query;
            Query="update CustomerService set decision='"+decision+"' where ordernumber='"+ordernum+"' ";
            InsertUpdateDelete.setData(Query,"Submit decision Successfully!");

        } catch (Exception e)
        {
            JOptionPane.showConfirmDialog(null, e);

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        CurrentOrderCSJPanel.setVisible(true);
        CurrentOrderComplainsJPanel.setVisible(false);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int ordernum=Integer.parseInt(jTextField2.getText());
        String decision=(String)jComboBox1.getSelectedItem();

        try
        {
            String Query;
            Query="update CustomerService set decision='"+decision+"' where ordernumber='"+ordernum+"' ";
            InsertUpdateDelete.setData(Query,"Update decision Successfully!");

        } catch (Exception e)
        {
            JOptionPane.showConfirmDialog(null, e);

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         DefaultTableModel model=(DefaultTableModel)jTable4.getModel();
        model.setRowCount(0);
        Table();
        DefaultTableModel model1=(DefaultTableModel)jTable5.getModel();
        model1.setRowCount(0);
        Table1();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CurrentOrderCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CurrentOrderCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CurrentOrderCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CurrentOrderCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CurrentOrderCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CurrentOrderCSJPanel;
    private javax.swing.JPanel CurrentOrderComplainsJPanel;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnback1;
    private javax.swing.JButton btnview1;
    private javax.swing.JComboBox<String> cmbProblem;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel lblComplain;
    private javax.swing.JLabel lblDecision;
    private javax.swing.JLabel lblDetail;
    private javax.swing.JLabel lblMarket;
    private javax.swing.JLabel lblOrderDate;
    private javax.swing.JLabel lblOrderNumber;
    private javax.swing.JLabel lblOrderType;
    private javax.swing.JLabel lblProblem;
    private javax.swing.JLabel lblServiceInProgress2;
    private javax.swing.JLabel lblServiceInProgress3;
    private javax.swing.JLabel lblTotalAmount;
    private javax.swing.JLabel lblUser;
    // End of variables declaration//GEN-END:variables
}
