/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import Pages.Login;
import javax.swing.JOptionPane;
import model.customer;
import model.customers;
import projects.InsertUpdateDelete;

/**
 *
 * @author evelyn
 */
public class CreateUser extends javax.swing.JPanel {

    /**
     * Creates new form Order
     */
    customers history;
    public CreateUser(customers history) {
        initComponents();
        this.history = history;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
//    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        btnconfirm = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 204, 0));
        jLabel2.setText("Address:");
        add(jLabel2);
        jLabel2.setBounds(260, 210, 180, 23);

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 204, 0));
        jLabel8.setText("Password:");
        add(jLabel8);
        jLabel8.setBounds(250, 160, 120, 23);

        jLabel4.setBackground(new java.awt.Color(204, 255, 204));
        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 204, 0));
        jLabel4.setText("User Name:");
        add(jLabel4);
        jLabel4.setBounds(240, 110, 120, 23);
        add(jTextField6);
        jTextField6.setBounds(350, 160, 207, 23);

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 204, 0));
        jLabel5.setText("Phone number:");
        add(jLabel5);
        jLabel5.setBounds(210, 250, 170, 30);
        add(jTextField7);
        jTextField7.setBounds(350, 110, 207, 23);
        add(jTextField5);
        jTextField5.setBounds(350, 210, 207, 23);
        add(jTextField2);
        jTextField2.setBounds(350, 260, 207, 23);
        add(jTextField3);
        jTextField3.setBounds(350, 400, 207, 23);

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 204, 0));
        jLabel6.setText("Role:");
        add(jLabel6);
        jLabel6.setBounds(290, 470, 180, 30);

        jComboBox1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Customer", "Delivery Person", "Restaurant Owner", "Bakery Owner", "Grocery Store Owner" }));
        add(jComboBox1);
        jComboBox1.setBounds(350, 470, 150, 30);

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 204, 0));
        jLabel9.setText("Email address:");
        add(jLabel9);
        jLabel9.setBounds(210, 400, 130, 23);

        btnconfirm.setBackground(new java.awt.Color(204, 255, 204));
        btnconfirm.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnconfirm.setForeground(new java.awt.Color(102, 204, 0));
        btnconfirm.setText("Confirm");
        btnconfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconfirmActionPerformed(evt);
            }
        });
        add(btnconfirm);
        btnconfirm.setBounds(610, 560, 120, 29);

        btnback.setBackground(new java.awt.Color(204, 255, 204));
        btnback.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnback.setForeground(new java.awt.Color(102, 204, 0));
        btnback.setText("Goback to Login");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        add(btnback);
        btnback.setBounds(560, 20, 200, 29);

        jComboBox2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "male", "female" }));
        add(jComboBox2);
        jComboBox2.setBounds(350, 310, 130, 29);

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 204, 0));
        jLabel10.setText("Zipcode:");
        add(jLabel10);
        jLabel10.setBounds(250, 360, 120, 23);
        add(jTextField8);
        jTextField8.setBounds(350, 360, 207, 23);

        jLabel3.setFont(new java.awt.Font("Kokonor", 1, 24)); // NOI18N
        jLabel3.setText("Create a user");
        add(jLabel3);
        jLabel3.setBounds(330, 70, 180, 30);

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 204, 0));
        jLabel7.setText("Gender:");
        add(jLabel7);
        jLabel7.setBounds(269, 310, 70, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/picture/1-1024x1024.jpeg"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 700);
    }// </editor-fold>//GEN-END:initComponents

    private void btnconfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconfirmActionPerformed
        // TODO add your handling code here:
        
        String Username = jTextField7.getText();
        int PostalCode = Integer.parseInt(jTextField8.getText());
        String PhoneNum = jTextField2.getText();
        String Password = jTextField6.getText();
        String Address = jTextField5.getText();
        String Gender = (String) jComboBox2.getSelectedItem();
        String EmailAdd = jTextField3.getText();
        String Role = (String) jComboBox1.getSelectedItem();
        
        
//        customer ct = history.addNewCustomer();
//        ct.setUsername(Username);
//        ct.setPostalCode(PostalCode);
//        ct.setPhoneNum(PhoneNum);
//        ct.setPassword(Password);
//        ct.setAddress(Address);
//        ct.setGender(Gender);
//        ct.setEmailAdd(EmailAdd);
        
        // Validation!!!!
        if(Username.equals("")|| String.valueOf(PostalCode).equals("") ||PhoneNum.equals("") ||Password.equals("") ||Address.equals("") ||EmailAdd.equals(""))
            JOptionPane.showConfirmDialog(null, "Every Filed is Required!");
        else
        {
            String Query; 
            Query="insert into person(username,zipcode,phone number,password,address,gender,email,role)values(?,?,?,?,?,?,?,?)";
            InsertUpdateDelete.setData(Query,"Registered Successfully");
            setVisible(true);   
     
        }
    }//GEN-LAST:event_btnconfirmActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed

        new Login().setVisible(true);
        // TODO add your handling code here;
        
        
      
    }//GEN-LAST:event_btnbackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnconfirm;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
