/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import Pages.Login;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import projects.InsertUpdateDelete;
import projects.Select;

/**
 *
 * @author chengzhishi
 */
public class DeliveryPersonJPanel extends javax.swing.JPanel {

    /**
     * Creates new form OrderJPanel
     */
    public DeliveryPersonJPanel() {
        initComponents();
        Table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
       public void Table(){
         
         
         //String marketname=Login.jTextField1.getText();
                       
           
       ResultSet rs=Select.getData("select * from orders ");
        DefaultTableModel model=(DefaultTableModel)jTable2.getModel();
        model.setRowCount(0);
        try {
            while(rs.next())
            {
                model.addRow(new Object[]{rs.getInt(2),rs.getString(3),rs.getString(4),rs.getString(6)});
            }
            rs.close();
                
            
        } catch (Exception e)
        {
            JOptionPane.showConfirmDialog(null, e);
        }
        
        
        String deliveryname=Login.jTextField1.getText();
        ResultSet rs1=Select.getData("select * from orders where deliveryperson='"+deliveryname+"' ");
        DefaultTableModel model2=(DefaultTableModel)jTable4.getModel();
        model2.setRowCount(0);
        try {
            while(rs1.next())
            {
                model2.addRow(new Object[]{rs1.getInt(2),rs1.getString(3),rs1.getString(4),rs1.getString(5),rs1.getString(6),rs1.getString(14)});
            }
            rs1.close();
                
            
        } catch (Exception e)
        {
            JOptionPane.showConfirmDialog(null, e);
        }
        
        
        
        
        
    }
       
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DeliveryPersonAll = new javax.swing.JPanel();
        lblOrder1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        lblOrder3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        DeliveryPersonAll.setLayout(null);

        lblOrder1.setFont(new java.awt.Font("Kokonor", 3, 24)); // NOI18N
        lblOrder1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOrder1.setText("ALl Order");
        DeliveryPersonAll.add(lblOrder1);
        lblOrder1.setBounds(0, 10, 814, 42);

        jTable2.setBackground(new java.awt.Color(204, 255, 204));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Order Number", "Market", "Address", "Customer Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        DeliveryPersonAll.add(jScrollPane2);
        jScrollPane2.setBounds(0, 50, 790, 237);

        jButton4.setBackground(new java.awt.Color(204, 255, 204));
        jButton4.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(102, 204, 0));
        jButton4.setText("Accept");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        DeliveryPersonAll.add(jButton4);
        jButton4.setBounds(630, 300, 130, 30);

        lblOrder3.setFont(new java.awt.Font("Kokonor", 3, 24)); // NOI18N
        lblOrder3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOrder3.setText("Accepted Order");
        DeliveryPersonAll.add(lblOrder3);
        lblOrder3.setBounds(0, 310, 814, 42);

        jButton1.setBackground(new java.awt.Color(204, 255, 204));
        jButton1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 204, 0));
        jButton1.setText("Deliveried");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        DeliveryPersonAll.add(jButton1);
        jButton1.setBounds(630, 610, 140, 30);

        jTable4.setBackground(new java.awt.Color(204, 255, 204));
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Order Number", "Market", "Address", "Customer", "C Address", "C Phone number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable4.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTable4ComponentShown(evt);
            }
        });
        jScrollPane4.setViewportView(jTable4);

        DeliveryPersonAll.add(jScrollPane4);
        jScrollPane4.setBounds(0, 350, 790, 237);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/picture/1-1024x1024.jpeg"))); // NOI18N
        DeliveryPersonAll.add(jLabel2);
        jLabel2.setBounds(0, 0, 790, 660);

        add(DeliveryPersonAll, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String name=Login.jTextField1.getText();
        int SelectedRowIndex = jTable2.getSelectedRow(); 
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        int ordernumber=(int)model.getValueAt(SelectedRowIndex,0);
        
        String Query;
            Query = "update orders set status ='On the way', deliveryperson='"+name+"' where orderID='"+ordernumber+"' ";
            InsertUpdateDelete.setData(Query, "Order accepted!");
            setVisible(true);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable4ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTable4ComponentShown
        // TODO add your handling code here:
        String deliveryname=Login.jTextField1.getText();
        ResultSet rs=Select.getData("select * from orders where deliveryperson='"+deliveryname+"' ");
        DefaultTableModel model=(DefaultTableModel)jTable4.getModel();
        model.setRowCount(0);
        try {
            while(rs.next())
            {
                model.addRow(new Object[]{rs.getInt(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(14)});
            }
            rs.close();
                
            
        } catch (Exception e)
        {
            JOptionPane.showConfirmDialog(null, e);
        }
    }//GEN-LAST:event_jTable4ComponentShown

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          String name=Login.jTextField1.getText();
        int SelectedRowIndex = jTable4.getSelectedRow(); 
        DefaultTableModel model = (DefaultTableModel) jTable4.getModel();
        int ordernumber=(int)model.getValueAt(SelectedRowIndex,0);
        
        String Query;
            Query = "update orders set status ='Completed' where orderID='"+ordernumber+"' ";
            InsertUpdateDelete.setData(Query, "Order deliveried Successfully!");
            setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DeliveryPersonAll;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable4;
    private javax.swing.JLabel lblOrder1;
    private javax.swing.JLabel lblOrder3;
    // End of variables declaration//GEN-END:variables
}
