/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Market;
import model.markets;
import projects.InsertUpdateDelete;



/**
 *
 * @author evelyn
 */
public class MarketOwnerfood extends javax.swing.JPanel {

    /**
     * Creates new form ReFood
     */
   
    public MarketOwnerfood() {
        initComponents();
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btncreate = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        AmountComboBox = new javax.swing.JComboBox<>();
        txtprice = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/picture/order.png"))); // NOI18N

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        btncreate.setBackground(new java.awt.Color(204, 255, 204));
        btncreate.setFont(new java.awt.Font("Helvetica Neue", 3, 18)); // NOI18N
        btncreate.setForeground(new java.awt.Color(0, 204, 0));
        btncreate.setText("Confirm");
        btncreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreateActionPerformed(evt);
            }
        });
        add(btncreate);
        btncreate.setBounds(540, 300, 120, 29);

        jLabel3.setBackground(new java.awt.Color(51, 102, 0));
        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 0));
        jLabel3.setText("Price:");
        add(jLabel3);
        jLabel3.setBounds(260, 250, 49, 23);

        jLabel4.setBackground(new java.awt.Color(51, 102, 0));
        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 0));
        jLabel4.setText("Amount:");
        add(jLabel4);
        jLabel4.setBounds(250, 200, 72, 23);

        AmountComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        add(AmountComboBox);
        AmountComboBox.setBounds(340, 200, 120, 23);
        add(txtprice);
        txtprice.setBounds(340, 250, 207, 23);

        jLabel6.setFont(new java.awt.Font("Kokonor", 1, 24)); // NOI18N
        jLabel6.setText("Manage food bag");
        add(jLabel6);
        jLabel6.setBounds(310, 160, 200, 42);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/picture/1-1024x1024.jpeg"))); // NOI18N
        add(jLabel5);
        jLabel5.setBounds(0, 0, 800, 680);
    }// </editor-fold>//GEN-END:initComponents

    private void btncreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreateActionPerformed
        // TODO add your handling code here:
        int amount = (int) AmountComboBox.getSelectedItem();
        Double price = Double.parseDouble(txtprice.getText());

        if (price.equals(0.0)) {
            JOptionPane.showConfirmDialog(null, "Every Filed is Required!");
        } else {
            String Query;
            Query = "insert into (amount,price)values(?,?,?,?,?,?,?)";
            InsertUpdateDelete.setData(Query, "Registered Successfully");
            JOptionPane.showMessageDialog(this, "New Bag is created!");
            setVisible(false);

        }


    }//GEN-LAST:event_btncreateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AmountComboBox;
    private javax.swing.JButton btncreate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtprice;
    // End of variables declaration//GEN-END:variables
}
