/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.time.LocalDate;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Market;
import model.OrderList;
import model.customers;
import model.markets;
import model.order;
import java.sql.*;
import model.Validation;
import projects.InsertUpdateDelete;
import projects.Select;

/**
 *
 * @author evelyn
 */
  
public class MarketRestaurantOwner extends javax.swing.JPanel {

    /**
     * Creates new form Resaurant
     */
   
    public MarketRestaurantOwner() {
        initComponents();
      
        Table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MarketRestaurant = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        searchtxt1 = new javax.swing.JTextField();
        btnconfirm1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        MarketRestaurantOrder = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMarket = new javax.swing.JTextField();
        txtuser = new javax.swing.JTextField();
        txtaddress = new javax.swing.JTextField();
        txtprice = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnback = new javax.swing.JButton();
        btnconfirm2 = new javax.swing.JButton();
        typeComboBox = new javax.swing.JComboBox<>();
        AmountComboBox = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.CardLayout());

        MarketRestaurant.setLayout(null);

        jTable2.setBackground(new java.awt.Color(204, 255, 204));
        jTable2.setFont(new java.awt.Font("Helvetica Neue", 3, 12)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Address", "Ranking Score", "Price"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        MarketRestaurant.add(jScrollPane2);
        jScrollPane2.setBounds(120, 200, 580, 225);

        searchtxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchtxt1ActionPerformed(evt);
            }
        });
        searchtxt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchtxt1KeyReleased(evt);
            }
        });
        MarketRestaurant.add(searchtxt1);
        searchtxt1.setBounds(380, 160, 180, 23);

        btnconfirm1.setBackground(new java.awt.Color(204, 255, 204));
        btnconfirm1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnconfirm1.setForeground(new java.awt.Color(102, 204, 0));
        btnconfirm1.setText("Confirm");
        btnconfirm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconfirm1ActionPerformed(evt);
            }
        });
        MarketRestaurant.add(btnconfirm1);
        btnconfirm1.setBounds(610, 460, 160, 30);

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 204, 0));
        jLabel12.setText("Search:");
        MarketRestaurant.add(jLabel12);
        jLabel12.setBounds(300, 150, 130, 40);

        jLabel13.setFont(new java.awt.Font("Kokonor", 1, 24)); // NOI18N
        jLabel13.setText("Find a Restaurant");
        MarketRestaurant.add(jLabel13);
        jLabel13.setBounds(350, 100, 200, 42);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/picture/1-1024x1024.jpeg"))); // NOI18N
        MarketRestaurant.add(jLabel14);
        jLabel14.setBounds(0, 0, 800, 740);

        add(MarketRestaurant, "card9");

        MarketRestaurantOrder.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 0));
        jLabel4.setText("User Name:");
        MarketRestaurantOrder.add(jLabel4);
        jLabel4.setBounds(240, 260, 180, 23);

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 0));
        jLabel8.setText("Amount:");
        MarketRestaurantOrder.add(jLabel8);
        jLabel8.setBounds(270, 220, 120, 23);

        jLabel5.setBackground(new java.awt.Color(204, 255, 204));
        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 0));
        jLabel5.setText("Market Address:");
        MarketRestaurantOrder.add(jLabel5);
        jLabel5.setBounds(200, 160, 150, 23);

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 0));
        jLabel7.setText("User Address:");
        MarketRestaurantOrder.add(jLabel7);
        jLabel7.setBounds(220, 310, 170, 30);
        MarketRestaurantOrder.add(txtMarket);
        txtMarket.setBounds(350, 110, 207, 23);
        MarketRestaurantOrder.add(txtuser);
        txtuser.setBounds(360, 270, 207, 23);
        MarketRestaurantOrder.add(txtaddress);
        txtaddress.setBounds(360, 320, 207, 23);
        MarketRestaurantOrder.add(txtprice);
        txtprice.setBounds(360, 440, 207, 23);

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 0));
        jLabel9.setText("Order type:");
        MarketRestaurantOrder.add(jLabel9);
        jLabel9.setBounds(240, 380, 130, 23);

        btnback.setBackground(new java.awt.Color(204, 255, 204));
        btnback.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnback.setForeground(new java.awt.Color(0, 51, 0));
        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        MarketRestaurantOrder.add(btnback);
        btnback.setBounds(630, 30, 120, 29);

        btnconfirm2.setBackground(new java.awt.Color(204, 255, 204));
        btnconfirm2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnconfirm2.setForeground(new java.awt.Color(0, 51, 0));
        btnconfirm2.setText("Confirm");
        btnconfirm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconfirm2ActionPerformed(evt);
            }
        });
        MarketRestaurantOrder.add(btnconfirm2);
        btnconfirm2.setBounds(340, 550, 120, 29);

        typeComboBox.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Delivery", "Pick-up" }));
        MarketRestaurantOrder.add(typeComboBox);
        typeComboBox.setBounds(360, 380, 130, 29);

        AmountComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1" }));
        MarketRestaurantOrder.add(AmountComboBox);
        AmountComboBox.setBounds(360, 220, 72, 23);

        jLabel10.setFont(new java.awt.Font("Kokonor", 1, 24)); // NOI18N
        jLabel10.setText("Create a order");
        MarketRestaurantOrder.add(jLabel10);
        jLabel10.setBounds(310, 60, 200, 42);

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 0));
        jLabel11.setText("Phone Number:");
        MarketRestaurantOrder.add(jLabel11);
        jLabel11.setBounds(190, 490, 150, 23);

        jLabel6.setBackground(new java.awt.Color(204, 255, 204));
        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 0));
        jLabel6.setText("Market Name:");
        MarketRestaurantOrder.add(jLabel6);
        jLabel6.setBounds(230, 110, 120, 23);
        MarketRestaurantOrder.add(jTextField1);
        jTextField1.setBounds(350, 160, 210, 30);

        jLabel15.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 51, 0));
        jLabel15.setText("Price:");
        MarketRestaurantOrder.add(jLabel15);
        jLabel15.setBounds(280, 440, 49, 23);
        MarketRestaurantOrder.add(jTextField2);
        jTextField2.setBounds(360, 490, 210, 30);

        jLabel16.setBackground(new java.awt.Color(204, 255, 204));
        jLabel16.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 51, 51));
        jLabel16.setText("One person only can buy one Magicbag!");
        MarketRestaurantOrder.add(jLabel16);
        jLabel16.setBounds(450, 210, 280, 40);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/picture/1-1024x1024.jpeg"))); // NOI18N
        jLabel1.setText("jLabel1");
        MarketRestaurantOrder.add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 740);

        add(MarketRestaurantOrder, "card2");
    }// </editor-fold>//GEN-END:initComponents
 public void Table(){
       ResultSet rs=Select.getData("select a.`Name`,a.Address,a.Category,a.Price, b.score from market a left join(select market, AVG(marketscore) as score from orders group by market)b on a.`Name`=b.market where a.Category='Restaurant' ");
        DefaultTableModel model=(DefaultTableModel)jTable2.getModel();
        model.setRowCount(0);
        try {
            while(rs.next())
            {
                model.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getFloat(5),rs.getFloat(4)});
            }
            rs.close();
                
            
        } catch (Exception e)
        {
            JOptionPane.showConfirmDialog(null, e);
        }
    }
    private void btnconfirm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconfirm2ActionPerformed
        // TODO add your handling code here:
        Date date = new Date();
        int orderID = (int) (Math.random() * 100000);
        String market = txtMarket.getText();
        String marketaddress=jTextField1.getText();
        int amount= Integer.parseInt((String)AmountComboBox.getSelectedItem());
        String user = txtuser.getText();
        String address = txtaddress.getText();
        String type = (String.valueOf(typeComboBox.getSelectedItem()));
        float price=Float.parseFloat(txtprice.getText());
        String Phone=jTextField2.getText();
        
       

        if (txtuser.getText().equals("") || txtaddress.getText().equals(""))
        JOptionPane.showConfirmDialog(null, "Every Filed is Required!");
        else if(Validation.isName(user)==false){
               JOptionPane.showMessageDialog(this, "Name should be letters.");
            }
              else if(Validation.isPhone(jTextField2.getText())==false){
               JOptionPane.showMessageDialog(this, "Phone number should be 10 numbers.");
            }
        else {

            String Query;
            Query="update market set amount=amount-1 where Name='"+market+"'";
            InsertUpdateDelete.setData(Query, "");
            
            String Query1;
            Query1 = "insert into orders(ordertime,orderID,market,marketaddress,customer,cusaddress,method,amout,price,status,phone) values('"+date+"','"+orderID+"','"+market+"','"+marketaddress+"','"+user+"','"+address+"','"+type+"','"+amount+"','"+price+"','Created','"+Phone+"')";
            InsertUpdateDelete.setData(Query1, "New Order is confirmed!");
      

            setVisible(true);
        }
    }//GEN-LAST:event_btnconfirm2ActionPerformed

    private void btnconfirm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconfirm1ActionPerformed
        // TODO add your handling code here:
     int selectedRow = jTable2.getSelectedRow();

        if(selectedRow == -1){
            JOptionPane.showMessageDialog(this,"Please select single Row.");
        }else{
             MarketRestaurantOrder.setVisible(true);
        MarketRestaurant.setVisible(false);
            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();

            String market = (String)model.getValueAt(selectedRow,0);
            String marketadd = (String)model.getValueAt(selectedRow,1);
           float price=(float)(model.getValueAt(selectedRow, 3));

            txtMarket.setText(market);
            txtMarket.setEditable(false);
            jTextField1.setText(marketadd);
            jTextField1.setEditable(false);
            txtprice.setText(String.valueOf(price));
            txtprice.setEditable(false);
        }
    }//GEN-LAST:event_btnconfirm1ActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
         MarketRestaurantOrder.setVisible(false);
        MarketRestaurant.setVisible(true);
    }//GEN-LAST:event_btnbackActionPerformed

    private void searchtxt1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchtxt1KeyReleased
        // TODO add your handling code here:
             String name=searchtxt1.getText();
        ResultSet rs=Select.getData("select * from market where Name like '%"+name+"%' and Category='Restaurant'");
        DefaultTableModel model=(DefaultTableModel)jTable2.getModel();
        model.setRowCount(0);
        try {
            while(rs.next())
            {
                model.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getInt(5),rs.getFloat(6)});

            }
            rs.close();

        } catch (Exception e)
        {
            JOptionPane.showConfirmDialog(null, e);

        }
    }//GEN-LAST:event_searchtxt1KeyReleased

    private void searchtxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchtxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchtxt1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AmountComboBox;
    private javax.swing.JPanel MarketRestaurant;
    private javax.swing.JPanel MarketRestaurantOrder;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnconfirm1;
    private javax.swing.JButton btnconfirm2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField searchtxt1;
    private javax.swing.JTextField txtMarket;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtuser;
    private javax.swing.JComboBox<String> typeComboBox;
    // End of variables declaration//GEN-END:variables
}
