/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import com.sun.jdi.connect.spi.Connection;
import java.beans.Statement;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import projects.InsertUpdateDelete;
import projects.Select;
import java.sql.*;
import javax.swing.table.TableModel;
import model.Validation;


/**
 *
 * @author evelyn
 */
public class MarketBakeryOwner extends javax.swing.JPanel {

    /**
     * Creates new form Resaurant
     * test
     */
   
    public MarketBakeryOwner() {
        initComponents();
        Table();
        txtMarket1.setEditable(false);
        txtMarketadd.setEditable(false);
        AmountComboBox1.setEditable(false);
        txtprice1.setEditable(false);
      
       
        
    }
    public void Table(){
       ResultSet rs=Select.getData("select a.`Name`,a.Address,a.Category,a.Price, b.score from market a left join(select market, AVG(marketscore) as score from orders group by market)b on a.`Name`=b.market where a.Category='Bakery' ");
        DefaultTableModel model=(DefaultTableModel)jTable3.getModel();
        model.setRowCount(0);
        try {
            while(rs.next())
            {
                model.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getFloat(5),rs.getFloat(4)});
            }
            rs.close();
                
            
        } catch (Exception e)
        {
            JOptionPane.showConfirmDialog(null, e);
        }
    }
            
    
    
    //public void Table(){
        /*DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.setRowCount(0);
        
        for(Market mar:markethistory.getHistory()){
            Object[] row = new Object[5];
            if(mar.getType()=="Bakery"){
           
            row[0] = mar.getMarketname();
            row[1] = mar.getAddress();
            row[2] = mar.getScore();
            row[3]= mar.getPrice();
            model.addRow(row);
            }
        }
        ResultSet rs=Select.getData("select * from market where Category='Bakery' ");
        DefaultTableModel model=(DefaultTableModel)jTable2.getModel();
        model.setRowCount(0);
        try {
            while(rs.next())
            {
                model.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(6),rs.getString(5)});
                
            }
            rs.close();
        
        } catch (Exception e) 
        {
            JOptionPane.showConfirmDialog(null, e);
            
        }
    }
    */
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
//    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        MarketBakery1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        searchtxt1 = new javax.swing.JTextField();
        btnconfirm3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        CustomerOrder1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtMarket1 = new javax.swing.JTextField();
        txtuser1 = new javax.swing.JTextField();
        txtaddress1 = new javax.swing.JTextField();
        txtprice1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtMarketadd = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        btnback1 = new javax.swing.JButton();
        btnconfirm1 = new javax.swing.JButton();
        typeComboBox1 = new javax.swing.JComboBox<>();
        AmountComboBox1 = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.CardLayout());

        MarketBakery1.setLayout(null);

        jTable3.setBackground(new java.awt.Color(204, 255, 204));
        jTable3.setFont(new java.awt.Font("Helvetica Neue", 3, 12)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Address", "Ranking Score", "Price"
            }
        ));
        jTable3.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTable3ComponentShown(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        MarketBakery1.add(jScrollPane3);
        jScrollPane3.setBounds(120, 200, 580, 225);

        searchtxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchtxt1ActionPerformed(evt);
            }
        });
        searchtxt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchtxt1KeyReleased(evt);
            }
        });
        MarketBakery1.add(searchtxt1);
        searchtxt1.setBounds(380, 150, 180, 23);

        btnconfirm3.setBackground(new java.awt.Color(204, 255, 204));
        btnconfirm3.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnconfirm3.setForeground(new java.awt.Color(102, 204, 0));
        btnconfirm3.setText("Confirm");
        btnconfirm3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconfirm3ActionPerformed(evt);
            }
        });
        MarketBakery1.add(btnconfirm3);
        btnconfirm3.setBounds(610, 460, 160, 30);

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 204, 0));
        jLabel6.setText("Search:");
        MarketBakery1.add(jLabel6);
        jLabel6.setBounds(300, 150, 90, 30);

        jLabel12.setFont(new java.awt.Font("Kokonor", 1, 24)); // NOI18N
        jLabel12.setText("Find a Bakery");
        MarketBakery1.add(jLabel12);
        jLabel12.setBounds(350, 100, 200, 42);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/picture/1-1024x1024.jpeg"))); // NOI18N
        MarketBakery1.add(jLabel15);
        jLabel15.setBounds(0, 0, 800, 740);

        jPanel1.add(MarketBakery1, "card10");

        CustomerOrder1.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 51, 51));
        jLabel13.setText("User Name:");
        CustomerOrder1.add(jLabel13);
        jLabel13.setBounds(230, 170, 180, 23);

        jLabel16.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 51, 51));
        jLabel16.setText("Amount:");
        CustomerOrder1.add(jLabel16);
        jLabel16.setBounds(250, 330, 120, 23);

        jLabel17.setBackground(new java.awt.Color(204, 255, 204));
        jLabel17.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 51, 51));
        jLabel17.setText("Market Name:");
        CustomerOrder1.add(jLabel17);
        jLabel17.setBounds(220, 70, 120, 23);

        jLabel18.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 51, 51));
        jLabel18.setText("User Address:");
        CustomerOrder1.add(jLabel18);
        jLabel18.setBounds(210, 210, 170, 30);

        txtMarket1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarket1ActionPerformed(evt);
            }
        });
        CustomerOrder1.add(txtMarket1);
        txtMarket1.setBounds(350, 70, 207, 23);
        CustomerOrder1.add(txtuser1);
        txtuser1.setBounds(350, 170, 207, 23);
        CustomerOrder1.add(txtaddress1);
        txtaddress1.setBounds(350, 220, 207, 23);

        txtprice1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprice1ActionPerformed(evt);
            }
        });
        CustomerOrder1.add(txtprice1);
        txtprice1.setBounds(350, 380, 207, 23);

        jLabel19.setBackground(new java.awt.Color(204, 255, 204));
        jLabel19.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 51, 51));
        jLabel19.setText("Market Address:");
        CustomerOrder1.add(jLabel19);
        jLabel19.setBounds(190, 120, 150, 23);

        txtMarketadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarketaddActionPerformed(evt);
            }
        });
        CustomerOrder1.add(txtMarketadd);
        txtMarketadd.setBounds(350, 120, 207, 23);

        jLabel20.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 51, 51));
        jLabel20.setText("Order type:");
        CustomerOrder1.add(jLabel20);
        jLabel20.setBounds(230, 270, 130, 23);

        btnback1.setBackground(new java.awt.Color(204, 255, 204));
        btnback1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnback1.setForeground(new java.awt.Color(102, 204, 0));
        btnback1.setText("Back");
        btnback1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnback1ActionPerformed(evt);
            }
        });
        CustomerOrder1.add(btnback1);
        btnback1.setBounds(630, 30, 120, 29);

        btnconfirm1.setBackground(new java.awt.Color(204, 255, 204));
        btnconfirm1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnconfirm1.setForeground(new java.awt.Color(51, 102, 0));
        btnconfirm1.setText("Confirm");
        btnconfirm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconfirm1ActionPerformed(evt);
            }
        });
        CustomerOrder1.add(btnconfirm1);
        btnconfirm1.setBounds(350, 530, 140, 40);

        typeComboBox1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        typeComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Delivery", "Pick-up" }));
        CustomerOrder1.add(typeComboBox1);
        typeComboBox1.setBounds(350, 270, 130, 29);

        AmountComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1" }));
        CustomerOrder1.add(AmountComboBox1);
        AmountComboBox1.setBounds(350, 330, 130, 23);

        jLabel21.setFont(new java.awt.Font("Kokonor", 1, 24)); // NOI18N
        jLabel21.setText("Create a order");
        CustomerOrder1.add(jLabel21);
        jLabel21.setBounds(310, 10, 200, 42);

        jLabel24.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 51, 51));
        jLabel24.setText("total Price:");
        CustomerOrder1.add(jLabel24);
        jLabel24.setBounds(230, 380, 100, 23);

        jLabel1.setBackground(new java.awt.Color(204, 255, 204));
        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("One person only can buy one Magicbag!");
        CustomerOrder1.add(jLabel1);
        jLabel1.setBounds(490, 330, 280, 30);

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 0));
        jLabel2.setText("Phone Number:");
        CustomerOrder1.add(jLabel2);
        jLabel2.setBounds(190, 430, 140, 30);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        CustomerOrder1.add(jTextField1);
        jTextField1.setBounds(350, 440, 200, 23);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/picture/1-1024x1024.jpeg"))); // NOI18N
        jLabel23.setText("jLabel1");
        CustomerOrder1.add(jLabel23);
        jLabel23.setBounds(0, 0, 800, 750);

        jPanel1.add(CustomerOrder1, "card9");

        add(jPanel1, "card4");
    }// </editor-fold>//GEN-END:initComponents

   
   
            
    private void jTable3ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTable3ComponentShown
        // TODO add your handling code here:

        /*  ResultSet rs=Select.getData("select * from market where Category='Bakery'");
        DefaultTableModel model=(DefaultTableModel)jTable2.getModel();
        model.setRowCount(0);
        try {
            while(rs.next())
            {
                model.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getInt(6),rs.getFloat(5)});
            }
            rs.close();

        } catch (Exception e)
        {
            JOptionPane.showConfirmDialog(null, e);

        }
        */

    }//GEN-LAST:event_jTable3ComponentShown

    private void searchtxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchtxt1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_searchtxt1ActionPerformed

    private void searchtxt1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchtxt1KeyReleased
        // TODO add your handling code here:
        /*DefaultTableModel table = (DefaultTableModel)jTable2.getModel();
        String search = searchtxt.getText();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(table);
        jTable2.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search));*/
        String name=searchtxt1.getText();
        ResultSet rs=Select.getData("select * from market where Name like '%"+name+"%' and Category='Bakery'");
        DefaultTableModel model=(DefaultTableModel)jTable3.getModel();
        model.setRowCount(0);
        try {
            while(rs.next())
            {
                model.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getInt(5),rs.getFloat(6)});

            }
            rs.close();

        } catch (Exception e)
        {
            JOptionPane.showConfirmDialog(null, e);

        }
    }//GEN-LAST:event_searchtxt1KeyReleased

    private void btnconfirm3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconfirm3ActionPerformed
        // TODO add your handling code here:
        //CustomerOrder1.setVisible(true);
        //MarketBakery1.setVisible(false);

        int selectedRow = jTable3.getSelectedRow();

        if(selectedRow == -1){
            JOptionPane.showMessageDialog(this,"Please select single Row.");
        }else{
             CustomerOrder1.setVisible(true);
        MarketBakery1.setVisible(false);
            DefaultTableModel model = (DefaultTableModel) jTable3.getModel();

            String market = (String)model.getValueAt(selectedRow,0);
            String marketadd = (String)model.getValueAt(selectedRow,1);
           float price=(float)(model.getValueAt(selectedRow, 3));

            txtMarket1.setText(market);
           txtMarket1.setEditable(false);
            txtMarketadd.setText(marketadd);
            txtMarketadd.setEditable(false);
            txtprice1.setText(String.valueOf(price));
            txtprice1.setEditable(false);
        }
    }//GEN-LAST:event_btnconfirm3ActionPerformed

    private void txtMarket1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarket1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarket1ActionPerformed

    private void txtprice1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprice1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprice1ActionPerformed

    private void txtMarketaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarketaddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarketaddActionPerformed

    private void btnback1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnback1ActionPerformed
        // TODO add your handling code here:
        CustomerOrder1.setVisible(false);
        MarketBakery1.setVisible(true);
    }//GEN-LAST:event_btnback1ActionPerformed

    private void btnconfirm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconfirm1ActionPerformed
        // TODO add your handling code here:

        Date date = new Date();
        int orderID = (int) (Math.random() * 100000);
        String market = txtMarket1.getText();
        String marketaddress=txtMarketadd.getText();
        int amount= Integer.parseInt((String)AmountComboBox1.getSelectedItem());
        String user = txtuser1.getText();
        String address = txtaddress1.getText();
        String type = (String.valueOf(typeComboBox1.getSelectedItem()));
        float price=Float.parseFloat(txtprice1.getText());
        String Phone=jTextField1.getText();
        
       

        if (txtuser1.getText().equals("") || txtaddress1.getText().equals(""))
        JOptionPane.showConfirmDialog(null, "Every Filed is Required!");
        else if(Validation.isName(user)==false){
               JOptionPane.showMessageDialog(this, "Name should be letters.");
            }
              else if(Validation.isPhone(jTextField1.getText())==false){
               JOptionPane.showMessageDialog(this, "Phone number should be 10 numbers.");
            }
              
        else {

            String Query;
            Query="update market set amount=amount-1 where Name='"+market+"'";
            InsertUpdateDelete.setData(Query, "");
            String Query1;
    
            Query1 = "insert into orders(ordertime,orderID,market,marketaddress,customer,cusaddress,method,amout,price,status,phone) values('"+date+"','"+orderID+"','"+market+"','"+marketaddress+"','"+user+"','"+address+"','"+type+"','"+amount+"','"+price+"','Created','"+Phone+"')";
            InsertUpdateDelete.setData(Query1, "New Order is confirmed!");
      

            // price 计算 String price = amount*
            //txtprice.setText();
            setVisible(true);
        }

    }//GEN-LAST:event_btnconfirm1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AmountComboBox1;
    private javax.swing.JPanel CustomerOrder1;
    private javax.swing.JPanel MarketBakery1;
    private javax.swing.JButton btnback1;
    private javax.swing.JButton btnconfirm1;
    private javax.swing.JButton btnconfirm3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField searchtxt1;
    private javax.swing.JTextField txtMarket1;
    private javax.swing.JTextField txtMarketadd;
    private javax.swing.JTextField txtaddress1;
    private javax.swing.JTextField txtprice1;
    private javax.swing.JTextField txtuser1;
    private javax.swing.JComboBox<String> typeComboBox1;
    // End of variables declaration//GEN-END:variables
}
