/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

/**
 *
 * @author chengzhishi
 */
public class RestaurantViewOrderJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CurrentOrderComplainsJPanel
     */
    public RestaurantViewOrderJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblComplain = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        lblOrderNumber = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        lblOrderType = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        lblOrderDate = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        lblMarket = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        lblProblem = new javax.swing.JLabel();
        cmbProblem = new javax.swing.JComboBox<>();
        lblTotalAmount = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        lblDetail = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblDecision = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setLayout(null);

        lblComplain.setFont(new java.awt.Font("Kokonor", 3, 24)); // NOI18N
        lblComplain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblComplain.setText("User Complain");
        add(lblComplain);
        lblComplain.setBounds(6, 10, 788, 42);

        lblUser.setBackground(new java.awt.Color(204, 255, 204));
        lblUser.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblUser.setForeground(new java.awt.Color(0, 102, 0));
        lblUser.setText("User:");
        add(lblUser);
        lblUser.setBounds(130, 70, 87, 23);
        add(jTextField1);
        jTextField1.setBounds(200, 70, 115, 23);

        lblOrderNumber.setBackground(new java.awt.Color(204, 255, 204));
        lblOrderNumber.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblOrderNumber.setForeground(new java.awt.Color(0, 102, 0));
        lblOrderNumber.setText("Order Number:");
        add(lblOrderNumber);
        lblOrderNumber.setBounds(410, 70, 127, 23);
        add(jTextField2);
        jTextField2.setBounds(550, 70, 115, 23);

        lblOrderType.setBackground(new java.awt.Color(204, 255, 204));
        lblOrderType.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblOrderType.setForeground(new java.awt.Color(0, 102, 0));
        lblOrderType.setText("Order Type:");
        add(lblOrderType);
        lblOrderType.setBounds(80, 150, 160, 23);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        add(jTextField3);
        jTextField3.setBounds(200, 150, 115, 23);

        lblOrderDate.setBackground(new java.awt.Color(204, 255, 204));
        lblOrderDate.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblOrderDate.setForeground(new java.awt.Color(0, 102, 0));
        lblOrderDate.setText("Order Date:");
        add(lblOrderDate);
        lblOrderDate.setBounds(440, 150, 150, 23);
        add(jTextField4);
        jTextField4.setBounds(550, 150, 115, 23);

        lblMarket.setBackground(new java.awt.Color(204, 255, 204));
        lblMarket.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblMarket.setForeground(new java.awt.Color(0, 102, 0));
        lblMarket.setText("Market:");
        add(lblMarket);
        lblMarket.setBounds(110, 220, 110, 23);
        add(jTextField5);
        jTextField5.setBounds(200, 220, 115, 23);

        lblProblem.setBackground(new java.awt.Color(204, 255, 204));
        lblProblem.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblProblem.setForeground(new java.awt.Color(0, 102, 0));
        lblProblem.setText("Problem:");
        add(lblProblem);
        lblProblem.setBounds(450, 200, 110, 23);

        cmbProblem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Wrong Order", "Not Received", "Delayed", "Missing Item" }));
        add(cmbProblem);
        cmbProblem.setBounds(550, 200, 115, 23);

        lblTotalAmount.setBackground(new java.awt.Color(204, 255, 204));
        lblTotalAmount.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblTotalAmount.setForeground(new java.awt.Color(0, 102, 0));
        lblTotalAmount.setText("Total Amount:");
        add(lblTotalAmount);
        lblTotalAmount.setBounds(60, 300, 170, 23);
        add(jTextField6);
        jTextField6.setBounds(200, 300, 115, 23);

        lblDetail.setBackground(new java.awt.Color(204, 255, 204));
        lblDetail.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblDetail.setForeground(new java.awt.Color(0, 102, 0));
        lblDetail.setText("Details:");
        add(lblDetail);
        lblDetail.setBounds(110, 380, 87, 23);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1);
        jScrollPane1.setBounds(190, 380, 234, 91);

        jLabel1.setBackground(new java.awt.Color(204, 255, 204));
        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 0));
        jLabel1.setText("Image Proof:");
        add(jLabel1);
        jLabel1.setBounds(460, 330, 160, 23);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Photo Here");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel2);
        jLabel2.setBounds(590, 330, 162, 177);

        btnSubmit.setBackground(new java.awt.Color(204, 255, 204));
        btnSubmit.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(102, 153, 0));
        btnSubmit.setText("Submit");
        add(btnSubmit);
        btnSubmit.setBounds(440, 610, 120, 29);

        btnBack.setBackground(new java.awt.Color(204, 255, 204));
        btnBack.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(102, 153, 0));
        btnBack.setText("Back");
        add(btnBack);
        btnBack.setBounds(590, 610, 120, 29);

        lblDecision.setBackground(new java.awt.Color(204, 255, 204));
        lblDecision.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblDecision.setForeground(new java.awt.Color(0, 102, 0));
        lblDecision.setText("Decision:");
        add(lblDecision);
        lblDecision.setBounds(100, 510, 130, 23);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "10% Refund", "50% Refund", "75% Refund", "100% Refund" }));
        add(jComboBox1);
        jComboBox1.setBounds(190, 510, 115, 23);

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/picture/1-1024x1024.jpeg"))); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(0, -3, 800, 700);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> cmbProblem;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel lblComplain;
    private javax.swing.JLabel lblDecision;
    private javax.swing.JLabel lblDetail;
    private javax.swing.JLabel lblMarket;
    private javax.swing.JLabel lblOrderDate;
    private javax.swing.JLabel lblOrderNumber;
    private javax.swing.JLabel lblOrderType;
    private javax.swing.JLabel lblProblem;
    private javax.swing.JLabel lblTotalAmount;
    private javax.swing.JLabel lblUser;
    // End of variables declaration//GEN-END:variables
}
