/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import Pages.Login;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import projects.InsertUpdateDelete;
import projects.Select;

/**
 *
 * @author chengzhishi
 */
public class RestaurantOwnerOrderJPanel extends javax.swing.JPanel {

    /**
     * Creates new form OrderJPanel
     */
    public RestaurantOwnerOrderJPanel() {
        initComponents();
        Table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public void Table(){
         
         
         String marketname=Login.jTextField1.getText();
                       
           
       ResultSet rs=Select.getData("select * from orders where market = '"+marketname+"' ");
        DefaultTableModel model=(DefaultTableModel)jTable2.getModel();
        model.setRowCount(0);
        try {
            while(rs.next())
            {
                model.addRow(new Object[]{rs.getString(1),rs.getInt(2),rs.getString(5),rs.getString(7),rs.getFloat(9),rs.getString(11)});
            }
            rs.close();
                
            
        } catch (Exception e)
        {
            JOptionPane.showConfirmDialog(null, e);
        }
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MarketOwnerOrder = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        btncancel1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        lblOrder1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ManageOrderJPanel = new javax.swing.JPanel();
        btnupdate = new javax.swing.JButton();
        btncreate = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        AmountComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtprice = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        MarketOwnerOrder.setLayout(null);

        jButton3.setBackground(new java.awt.Color(204, 255, 204));
        jButton3.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 153, 0));
        jButton3.setText("Finished");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        MarketOwnerOrder.add(jButton3);
        jButton3.setBounds(590, 530, 130, 30);

        btncancel1.setBackground(new java.awt.Color(204, 255, 204));
        btncancel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btncancel1.setForeground(new java.awt.Color(102, 153, 0));
        btncancel1.setText("Cancel");
        btncancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancel1ActionPerformed(evt);
            }
        });
        MarketOwnerOrder.add(btncancel1);
        btncancel1.setBounds(590, 370, 130, 29);

        jButton5.setBackground(new java.awt.Color(204, 255, 204));
        jButton5.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(51, 153, 0));
        jButton5.setText("Accept");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        MarketOwnerOrder.add(jButton5);
        jButton5.setBounds(590, 450, 130, 30);

        jTable2.setBackground(new java.awt.Color(204, 255, 204));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Order Date", "Order Number", "Customer", "Order Type", "Price", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        MarketOwnerOrder.add(jScrollPane2);
        jScrollPane2.setBounds(10, 120, 790, 237);

        jButton4.setBackground(new java.awt.Color(204, 255, 204));
        jButton4.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(102, 204, 0));
        jButton4.setText("Manage bag");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        MarketOwnerOrder.add(jButton4);
        jButton4.setBounds(560, 20, 210, 30);

        lblOrder1.setFont(new java.awt.Font("Kokonor", 3, 24)); // NOI18N
        lblOrder1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOrder1.setText("Market Orders");
        MarketOwnerOrder.add(lblOrder1);
        lblOrder1.setBounds(0, 60, 814, 42);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/picture/1-1024x1024.jpeg"))); // NOI18N
        MarketOwnerOrder.add(jLabel2);
        jLabel2.setBounds(0, 0, 800, 680);

        add(MarketOwnerOrder, "card2");

        ManageOrderJPanel.setLayout(null);

        btnupdate.setBackground(new java.awt.Color(204, 255, 204));
        btnupdate.setFont(new java.awt.Font("Helvetica Neue", 3, 18)); // NOI18N
        btnupdate.setForeground(new java.awt.Color(0, 204, 51));
        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        ManageOrderJPanel.add(btnupdate);
        btnupdate.setBounds(540, 410, 120, 29);

        btncreate.setBackground(new java.awt.Color(204, 255, 204));
        btncreate.setFont(new java.awt.Font("Helvetica Neue", 3, 18)); // NOI18N
        btncreate.setForeground(new java.awt.Color(0, 204, 0));
        btncreate.setText("Create");
        btncreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreateActionPerformed(evt);
            }
        });
        ManageOrderJPanel.add(btncreate);
        btncreate.setBounds(540, 340, 120, 29);

        jLabel4.setBackground(new java.awt.Color(51, 102, 0));
        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 0));
        jLabel4.setText("Price:");
        ManageOrderJPanel.add(jLabel4);
        jLabel4.setBounds(270, 290, 49, 23);

        AmountComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));
        ManageOrderJPanel.add(AmountComboBox);
        AmountComboBox.setBounds(390, 230, 120, 23);

        jLabel5.setBackground(new java.awt.Color(51, 102, 0));
        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 0));
        jLabel5.setText("Amount:");
        ManageOrderJPanel.add(jLabel5);
        jLabel5.setBounds(250, 230, 72, 23);
        ManageOrderJPanel.add(txtprice);
        txtprice.setBounds(390, 290, 120, 23);

        jLabel6.setFont(new java.awt.Font("Kokonor", 1, 24)); // NOI18N
        jLabel6.setText("Manage food bag");
        ManageOrderJPanel.add(jLabel6);
        jLabel6.setBounds(310, 160, 200, 42);

        jButton1.setBackground(new java.awt.Color(204, 255, 204));
        jButton1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 51));
        jButton1.setText("Goback");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        ManageOrderJPanel.add(jButton1);
        jButton1.setBounds(580, 50, 130, 30);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/picture/1-1024x1024.jpeg"))); // NOI18N
        ManageOrderJPanel.add(jLabel7);
        jLabel7.setBounds(0, 0, 800, 680);

        add(ManageOrderJPanel, "card3");
    }// </editor-fold>//GEN-END:initComponents

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
      int amount =Integer.parseInt((String)AmountComboBox.getSelectedItem());

        float price=Float.parseFloat(txtprice.getText());
        
        String name=Login.jTextField1.getText();

 
         if(String.valueOf(price).equals(""))
            JOptionPane.showConfirmDialog(null, "Price is Required!");
        else
        {
            String Query;
            Query="update market set amount='"+amount+"', Price='"+price+"' where Name='"+name+"' ";
            
            InsertUpdateDelete.setData(Query,"Updated Successfully");
            setVisible(true);
     
        }
         
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btncreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreateActionPerformed
        // TODO add your handling code here:
        int amount =Integer.parseInt((String)AmountComboBox.getSelectedItem());

        float price=Float.parseFloat(txtprice.getText());
        
        String name=Login.jTextField1.getText();

 
         if(String.valueOf(price).equals(""))
            JOptionPane.showConfirmDialog(null, "Price is Required!");
        else
        {
            String Query;
            Query="insert into market(amount,Price) values('"+amount+"','"+price+"') where Name='"+name+"' ";
            
            InsertUpdateDelete.setData(Query,"Added Successfully");
            setVisible(true);
     
        }

    }//GEN-LAST:event_btncreateActionPerformed

    private void btncancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancel1ActionPerformed
        // TODO add your handling code here:
        int SelectedRowIndex = jTable2.getSelectedRow(); 
     
        

        if(jTable2.getSelectedRowCount()==1){
            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        int ordernumber=(int)model.getValueAt(SelectedRowIndex,1);
           try 
        {
             String Query;
             Query="delete from orders where orderID='"+ordernumber+"' ";
             InsertUpdateDelete.setData(Query,"Order conceled successfully!");
       
        } catch (Exception e)
        {
            JOptionPane.showConfirmDialog(null, e);
            
        }
        }else{
            if(jTable2.getRowCount()==0){
                JOptionPane.showMessageDialog(this,"Table is Empty");
         
            }
            else{
                JOptionPane.showMessageDialog(this,"Please select single Row for delete.");
            }
        }

    }//GEN-LAST:event_btncancel1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        int SelectedRowIndex = jTable2.getSelectedRow(); 
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        int ordernumber=(int)model.getValueAt(SelectedRowIndex,1);
        
        String Query;
            Query = "update orders set status ='Preparing' where orderID='"+ordernumber+"' ";
            InsertUpdateDelete.setData(Query, "Order is accepted!");
            
            String Query1;
            Query1 = "update CustomerService set status ='Preparing' where ordernumber='"+ordernumber+"' ";
            InsertUpdateDelete.setData(Query1, "");
            
            setVisible(true);
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
          int SelectedRowIndex = jTable2.getSelectedRow(); 
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        int ordernumber=(int)model.getValueAt(SelectedRowIndex,1);
        
        String Query;
            Query = "update orders set status ='Ready to pick up' where orderID='"+ordernumber+"' ";
            InsertUpdateDelete.setData(Query, "Order is finished!");
            String Query1;
            Query1 = "update CustomerService set status ='Ready to pick up' where orderID='"+ordernumber+"' ";
            InsertUpdateDelete.setData(Query1, "");
            
            setVisible(true);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        ManageOrderJPanel.setVisible(true);
        MarketOwnerOrder.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MarketOwnerOrder.setVisible(true);
        ManageOrderJPanel.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AmountComboBox;
    private javax.swing.JPanel ManageOrderJPanel;
    private javax.swing.JPanel MarketOwnerOrder;
    private javax.swing.JButton btncancel1;
    private javax.swing.JButton btncreate;
    private javax.swing.JButton btnupdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblOrder1;
    private javax.swing.JTextField txtprice;
    // End of variables declaration//GEN-END:variables
}
