/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import com.mysql.fabric.xmlrpc.base.Value;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Market;
import model.OrderList;
import model.deliveryperson;
import model.deliverypersons;
import model.markets;
import model.order;
import projects.InsertUpdateDelete;
import projects.Select;

/**
 *
 * @author evelyn
 */
public class SystemRankingJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SystemMarketJPanel
     */
    /*markets markethistory;
    deliverypersons dphistory;
    OrderList orderhistory;*/
    public SystemRankingJPanel() {
        initComponents();
        Table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
       public void Table(){
       ResultSet rs=Select.getData("select * from orders");
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        model.setRowCount(0);
        try {
            while(rs.next())
            {
                model.addRow(new Object[]{rs.getInt(2),rs.getString(7), rs.getString(13),rs.getString(12)});
            }
            rs.close();
                
            
        } catch (Exception e)
        {
            JOptionPane.showConfirmDialog(null, e);
        }
    }
       
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        btncreate = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(102, 153, 0));
        setLayout(null);

        jTable1.setBackground(new java.awt.Color(204, 255, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Order Number", "Order Type", "Score of Market", "Score of Delivery Person"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1);
        jScrollPane1.setBounds(70, 40, 640, 231);

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 0));
        jLabel4.setText("Score about delivery person:");
        add(jLabel4);
        jLabel4.setBounds(40, 510, 245, 23);

        jComboBox2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        add(jComboBox2);
        jComboBox2.setBounds(330, 510, 90, 30);

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 0));
        jLabel7.setText("Score about market:");
        add(jLabel7);
        jLabel7.setBounds(40, 410, 173, 23);

        jComboBox3.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        add(jComboBox3);
        jComboBox3.setBounds(240, 403, 90, 30);

        btncreate.setBackground(new java.awt.Color(204, 255, 204));
        btncreate.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btncreate.setForeground(new java.awt.Color(102, 153, 0));
        btncreate.setText("Create");
        btncreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreateActionPerformed(evt);
            }
        });
        add(btncreate);
        btncreate.setBounds(440, 360, 100, 29);

        btnupdate.setBackground(new java.awt.Color(204, 255, 204));
        btnupdate.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnupdate.setForeground(new java.awt.Color(102, 153, 0));
        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        add(btnupdate);
        btnupdate.setBounds(601, 360, 110, 29);

        btndelete.setBackground(new java.awt.Color(204, 255, 204));
        btndelete.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btndelete.setForeground(new java.awt.Color(102, 153, 0));
        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        add(btndelete);
        btndelete.setBounds(600, 450, 110, 29);

        jLabel8.setFont(new java.awt.Font("Kokonor", 1, 24)); // NOI18N
        jLabel8.setText("Ranking Administration");
        add(jLabel8);
        jLabel8.setBounds(230, 0, 310, 50);

        jButton1.setBackground(new java.awt.Color(204, 255, 204));
        jButton1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 0));
        jButton1.setText("Read");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(440, 450, 100, 30);

        jComboBox1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        add(jComboBox1);
        jComboBox1.setBounds(190, 300, 140, 30);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 0));
        jLabel2.setText("Order Number:");
        add(jLabel2);
        jLabel2.setBounds(40, 300, 127, 23);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/picture/1-1024x1024.jpeg"))); // NOI18N
        add(jLabel6);
        jLabel6.setBounds(0, 0, 800, 760);
    }// </editor-fold>//GEN-END:initComponents

    private void btncreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreateActionPerformed
        // TODO add your handling code here:
   
       
      int ordernumber=Integer.parseInt((String)jComboBox1.getSelectedItem());
      //int deliscore=Integer.parseInt((String)jComboBox2.getSelectedItem());
      int marketscore=Integer.parseInt((String)jComboBox3.getSelectedItem());
      ResultSet rs=Select.getData("select * from orders where orderID='"+ordernumber+"'");
     try {
            while(rs.next())
            {
                if(rs.getString(7).equals("Pick-up")){
                    String Query1;
            Query1="update orders set marketscore='"+marketscore+"' where orderID='"+ordernumber+"' ";
            //Query="insert into person(username,zipcode,phone number,password,address,gender,email,role)values(?,?,?,?,?,?,?,?)";
            InsertUpdateDelete.setData(Query1,"Added Score Successfully");
                
            }
                else{
                    int deliscore=Integer.parseInt((String)jComboBox2.getSelectedItem());
                    String Query;
            Query="update orders set Deliveryscore='"+deliscore+"', marketscore='"+marketscore+"' where orderID='"+ordernumber+"' ";
            //Query="insert into person(username,zipcode,phone number,password,address,gender,email,role)values(?,?,?,?,?,?,?,?)";
            InsertUpdateDelete.setData(Query,"Added Score Successfully");
                    
                }
            }
            rs.close();
                
            
        } catch (Exception e)
        {
            JOptionPane.showConfirmDialog(null, e);
        }
      
            setVisible(true);
    
    }//GEN-LAST:event_btncreateActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
 
  
      int ordernumber=Integer.parseInt(jComboBox1.getSelectedItem().toString());
      //int deliscore=Integer.parseInt((String)jComboBox2.getSelectedItem());
      int marketscore=Integer.parseInt((String)jComboBox3.getSelectedItem());
  
     ResultSet rs=Select.getData("select * from orders where orderID='"+ordernumber+"'");
     try {
            while(rs.next())
            {
                if(rs.getString(7).equals("Pick-up")){
                    String Query1;
            Query1="update orders set marketscore='"+marketscore+"' where orderID='"+ordernumber+"' ";
            //Query="insert into person(username,zipcode,phone number,password,address,gender,email,role)values(?,?,?,?,?,?,?,?)";
            InsertUpdateDelete.setData(Query1,"Added Score Successfully");
                
            }
                else{
                    int deliscore=Integer.parseInt((String)jComboBox2.getSelectedItem());
                    String Query;
            Query="update orders set Deliveryscore='"+deliscore+"', marketscore='"+marketscore+"' where orderID='"+ordernumber+"' ";
            //Query="insert into person(username,zipcode,phone number,password,address,gender,email,role)values(?,?,?,?,?,?,?,?)";
            InsertUpdateDelete.setData(Query,"Added Score Successfully");
                    
                }
            }
            rs.close();
                
            
        } catch (Exception e)
        {
            JOptionPane.showConfirmDialog(null, e);
        }
      
            setVisible(true);
    
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
          int SelectedRowIndex = jTable1.getSelectedRow();
       
      
        if (SelectedRowIndex < 0){
            
            JOptionPane.showMessageDialog(this, "Please Select a Row to Delete.");
            return;
    }
        if (SelectedRowIndex >= 0){
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int ordernumber=(int)model.getValueAt(SelectedRowIndex,0);
        try 
        {
             String Query;
             Query="update orders set Deliveryscore=null, marketscore=null  where orderID='"+ordernumber+"' ";
             InsertUpdateDelete.setData(Query,"Deleted Score Successfully!");
       
        } catch (Exception e)
        {
            JOptionPane.showConfirmDialog(null, e);
            
        }
    
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         int index=jTable1.getSelectedRow();
          DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        
      
         if(index<0){
            ResultSet rs=Select.getData("select * from orders where Deliveryscore is null and marketscore is null");
            //ResultSet rs1=Select.getData("select * from orders where orderID='"+number+"'");
        
        try {
            while(rs.next())
            {
                jComboBox1.addItem(String.valueOf(rs.getInt(2)));
                int number=Integer.parseInt(jComboBox1.getSelectedItem().toString());
                ResultSet rs1=Select.getData("select * from orders where orderID='"+number+"'");
                while(rs1.next())
                {
                if(rs1.getString(7).equals("Pick-up")){
                    jComboBox2.setEnabled(false);
                
                }
                else{
                    jComboBox2.setEnabled(true);
                    
                    
                }
            
                
            }
               
                
            }
            rs.close();
                
            
        } catch (Exception e)
        {
            JOptionPane.showConfirmDialog(null, e);
        }
                 
         }
    
         else if (index >= 0){
             String typeString=model.getValueAt(index, 1).toString();
        //DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        jComboBox1.addItem(String.valueOf((int)model.getValueAt(index,0)));
        jComboBox1.setEnabled(false);
        
        jComboBox3.setSelectedItem((String)model.getValueAt(index, 1));
        jComboBox2.setSelectedItem((String)model.getValueAt(index, 2));
        if(typeString.equals("Pick-up")){
            jComboBox2.setEnabled(false);
            
        }
        else{
            jComboBox2.setEnabled(true);
            
        }
     
           }
        
    }//GEN-LAST:event_jButton1ActionPerformed
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncreate;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnupdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
