/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import com.sun.net.httpserver.Authenticator;
import javax.naming.spi.DirStateFactory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Market;
import model.OrderList;
import model.deliveryperson;
import model.deliverypersons;
import model.markets;
import model.order;
import projects.InsertUpdateDelete;
import  java.sql.*;
import model.Validation;
import projects.Select;

/**
 *
 * @author evelyn
 */
public class SystemUserJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SystemMarketJPanel
     */
    /*markets markethistory;
    deliverypersons dphistory;
    OrderList orderhistory;*/
    public SystemUserJPanel() {
        initComponents();
        Table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public void Table(){
       ResultSet rs=Select.getData("select * from person");
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        model.setRowCount(0);
        try {
            while(rs.next())
            {
                model.addRow(new Object[]{rs.getString(1),rs.getString(4),rs.getString(8),rs.getString(5),rs.getString(3),rs.getString(6),rs.getInt(2),rs.getString(7)});
            }
            rs.close();
                
            
        } catch (Exception e)
        {
            JOptionPane.showConfirmDialog(null, e);
        }
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btncreate = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btnread = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(102, 153, 0));
        setLayout(null);

        jTable1.setBackground(new java.awt.Color(204, 255, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Username", "Password", "Role", "Address", "Phone", "Gender", "Zipcode", "Email"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1);
        jScrollPane1.setBounds(20, 40, 770, 230);

        btncreate.setBackground(new java.awt.Color(204, 255, 204));
        btncreate.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btncreate.setForeground(new java.awt.Color(102, 153, 0));
        btncreate.setText("Create");
        btncreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreateActionPerformed(evt);
            }
        });
        add(btncreate);
        btncreate.setBounds(500, 310, 100, 29);

        btnupdate.setBackground(new java.awt.Color(204, 255, 204));
        btnupdate.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnupdate.setForeground(new java.awt.Color(102, 153, 0));
        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        add(btnupdate);
        btnupdate.setBounds(681, 310, 100, 29);

        btnread.setBackground(new java.awt.Color(204, 255, 204));
        btnread.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnread.setForeground(new java.awt.Color(102, 153, 0));
        btnread.setText("Read");
        btnread.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreadActionPerformed(evt);
            }
        });
        add(btnread);
        btnread.setBounds(500, 390, 110, 29);

        btndelete.setBackground(new java.awt.Color(204, 255, 204));
        btndelete.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btndelete.setForeground(new java.awt.Color(102, 153, 0));
        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        add(btndelete);
        btndelete.setBounds(684, 390, 100, 29);

        jLabel4.setBackground(new java.awt.Color(204, 255, 204));
        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 0));
        jLabel4.setText("User Name:");
        add(jLabel4);
        jLabel4.setBounds(60, 280, 120, 23);

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        add(jTextField7);
        jTextField7.setBounds(170, 280, 207, 30);

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 0));
        jLabel9.setText("Password:");
        add(jLabel9);
        jLabel9.setBounds(60, 340, 120, 23);

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        add(jTextField6);
        jTextField6.setBounds(170, 340, 207, 30);

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 0));
        jLabel2.setText("Role:");
        add(jLabel2);
        jLabel2.setBounds(460, 600, 50, 23);

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        add(jTextField5);
        jTextField5.setBounds(170, 400, 207, 30);

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 0));
        jLabel5.setText("Phone number:");
        add(jLabel5);
        jLabel5.setBounds(20, 460, 170, 30);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        add(jTextField2);
        jTextField2.setBounds(170, 470, 207, 30);

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 0));
        jLabel7.setText("Gender:");
        add(jLabel7);
        jLabel7.setBounds(440, 510, 70, 30);

        jComboBox2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "male", "female" }));
        add(jComboBox2);
        jComboBox2.setBounds(510, 510, 130, 29);

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 0));
        jLabel10.setText("Zipcode:");
        add(jLabel10);
        jLabel10.setBounds(70, 530, 120, 23);

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        add(jTextField8);
        jTextField8.setBounds(170, 530, 207, 30);

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 0));
        jLabel11.setText("Email address:");
        add(jLabel11);
        jLabel11.setBounds(30, 600, 130, 23);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        add(jTextField3);
        jTextField3.setBounds(170, 600, 207, 30);

        jComboBox1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Customer", "Delivery Person", "Restaurant Owner", "Bakery Owner", "Grocery Store Owner", "Current Order Customer Representative", "Finished Order Customer Representative", " " }));
        add(jComboBox1);
        jComboBox1.setBounds(510, 600, 280, 29);

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 0));
        jLabel3.setText("Address:");
        add(jLabel3);
        jLabel3.setBounds(70, 400, 180, 23);

        jLabel8.setFont(new java.awt.Font("Kokonor", 1, 24)); // NOI18N
        jLabel8.setText("User Administration");
        add(jLabel8);
        jLabel8.setBounds(230, 0, 310, 50);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/picture/1-1024x1024.jpeg"))); // NOI18N
        add(jLabel6);
        jLabel6.setBounds(0, 0, 800, 760);
    }// </editor-fold>//GEN-END:initComponents

    private void btncreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreateActionPerformed
        // TODO add your handling code here:
  
        String name=jTextField7.getText();
        String passwordString=jTextField6.getText();
        String address=jTextField5.getText();
        String phone=jTextField2.getText();
        String zipString=jTextField8.getText();
        String emailString=jTextField3.getText();
        String genderString=jComboBox2.getSelectedItem().toString();
        String roleString=jComboBox1.getSelectedItem().toString();
        ResultSet rs=Select.getData("select * from person where username='"+name+"'");
   
        try 
        {
            if(rs.next()){
                
                    JOptionPane.showConfirmDialog(null, "This user already existed, please input another one!");
                }
            else if(Validation.isName(name)==false){
               JOptionPane.showMessageDialog(this, "Name should be letters.");
            }
              else if(Validation.isPhone(jTextField2.getText())==false){
               JOptionPane.showMessageDialog(this, "Phone number should be 10 numbers.");
            }
              else if(Validation.isZipcode(jTextField8.getText())==false){
               JOptionPane.showMessageDialog(this, "Postalcode should be 5 numbers.");
            }
               else if(Validation.isEmail(jTextField3.getText())==false){
               JOptionPane.showMessageDialog(this, "Email address should be correct format.");
            }
                else{
           
             String Query;
             Query="insert into person(username,zipcode,phonenumber,password,address,gender,email,role) values('"+name+"','"+zipString+"','"+phone+"','"+passwordString+"','"+address+"','"+genderString+"','"+emailString+"','"+roleString+"')";
             InsertUpdateDelete.setData(Query,"Created Successfully!");
                }
       
        } catch (Exception e)
        {
            JOptionPane.showConfirmDialog(null, e);
            
        }
        
        
        
    }//GEN-LAST:event_btncreateActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        String name=jTextField7.getText();
        String passwordString=jTextField6.getText();
        String address=jTextField5.getText();
        String phone=jTextField2.getText();
        int zipString=Integer.parseInt(jTextField8.getText());
        String emailString=jTextField3.getText();
        String genderString=jComboBox2.getSelectedItem().toString();
        String roleString=jComboBox1.getSelectedItem().toString();
        //ResultSet rs=Select.getData("select * from person");
         
              if(Validation.isPhone(jTextField2.getText())==false){
               JOptionPane.showMessageDialog(this, "Phone number should be 10 numbers.");
            }
              else if(Validation.isZipcode(jTextField8.getText())==false){
               JOptionPane.showMessageDialog(this, "Postalcode should be 5 numbers.");
            }
               else if(Validation.isEmail(jTextField3.getText())==false){
               JOptionPane.showMessageDialog(this, "Email address should be correct format.");
            }
               else{
         try 
        {
           
             String Query;
             Query="update person set zipcode='"+zipString+"', phonenumber='"+phone+"', password='"+passwordString+"', address='"+address+"', gender='"+genderString+"',email='"+emailString+"', role='"+roleString+"' where username='"+name+"' ";
             InsertUpdateDelete.setData(Query,"Updated Successfully!");
                
       
        } catch (Exception e)
        {
            JOptionPane.showConfirmDialog(null, e);
            
        }
               }
        
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnreadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreadActionPerformed
        // TODO add your handling code here:
          int index=jTable1.getSelectedRow();
    
           if (index >= 0){
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        jTextField7.setText((String)model.getValueAt(index, 0));
               jTextField7.setEditable(false);
               jTextField6.setText((String)model.getValueAt(index, 1));
               jTextField5.setText((String)model.getValueAt(index, 3));
               jTextField2.setText((String)model.getValueAt(index, 4));
               jTextField8.setText(String.valueOf((int)model.getValueAt(index, 6)));
               jTextField3.setText((String)model.getValueAt(index, 7));
               jComboBox2.setSelectedItem(model.getValueAt(index, 5).toString());
               jComboBox1.setSelectedItem(model.getValueAt(index, 2).toString());
               
               
       
           }
        
    }//GEN-LAST:event_btnreadActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        int SelectedRowIndex = jTable1.getSelectedRow();
       
      
        if (SelectedRowIndex < 0){
            
            JOptionPane.showMessageDialog(this, "Please Select a Row to Delete.");
            return;
    }
        if (SelectedRowIndex >= 0){
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        String name=(String)model.getValueAt(SelectedRowIndex,0);
        try 
        {
             String Query;
             Query="delete from person where username='"+name+"' ";
             InsertUpdateDelete.setData(Query,"Deleted Successfully!");
       
        } catch (Exception e)
        {
            JOptionPane.showConfirmDialog(null, e);
            
        }
    
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncreate;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnread;
    private javax.swing.JButton btnupdate;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
