/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Market;
import model.markets;
import model.order;
import projects.InsertUpdateDelete;
import projects.*;
import java.sql.*;
import model.Validation;

/**
 *
 * @author evelyn
 */
public class SystemMarketJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SystemMarketJPanel
     */
  
    public SystemMarketJPanel() {
        initComponents();
        Table();
       
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
     public void Table(){
       ResultSet rs=Select.getData("select * from market");
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        model.setRowCount(0);
        try {
            while(rs.next())
            {
                model.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getInt(4),rs.getFloat(6)});
            }
            rs.close();
                
            
        } catch (Exception e)
        {
            JOptionPane.showConfirmDialog(null, e);
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        TypeCombo = new javax.swing.JComboBox<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        btncreate = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(102, 153, 0));
        setLayout(null);

        jTable1.setBackground(new java.awt.Color(204, 255, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Address", "Type", "Amount", "Price"
            }
        ));
        jTable1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jTable1ComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1);
        jScrollPane1.setBounds(72, 60, 610, 231);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("Name:");
        add(jLabel1);
        jLabel1.setBounds(70, 360, 54, 23);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("Address:");
        add(jLabel2);
        jLabel2.setBounds(60, 430, 76, 23);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setText("Type:");
        add(jLabel3);
        jLabel3.setBounds(80, 500, 46, 23);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Price:");
        add(jLabel5);
        jLabel5.setBounds(80, 630, 49, 23);

        jLabel7.setFont(new java.awt.Font("Kokonor", 1, 24)); // NOI18N
        jLabel7.setText("Market Administration");
        add(jLabel7);
        jLabel7.setBounds(270, 0, 310, 50);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1);
        jTextField1.setBounds(150, 360, 120, 30);
        add(jTextField2);
        jTextField2.setBounds(150, 630, 120, 30);

        TypeCombo.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        TypeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bakery", "Restaurant", "Grocery", " " }));
        add(TypeCombo);
        TypeCombo.setBounds(150, 500, 120, 29);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        add(jComboBox1);
        jComboBox1.setBounds(150, 560, 120, 30);

        btncreate.setBackground(new java.awt.Color(204, 255, 204));
        btncreate.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btncreate.setForeground(new java.awt.Color(102, 153, 0));
        btncreate.setText("Create");
        btncreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreateActionPerformed(evt);
            }
        });
        add(btncreate);
        btncreate.setBounds(326, 470, 100, 29);

        btnupdate.setBackground(new java.awt.Color(204, 255, 204));
        btnupdate.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnupdate.setForeground(new java.awt.Color(102, 153, 0));
        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        add(btnupdate);
        btnupdate.setBounds(570, 470, 100, 29);

        btndelete.setBackground(new java.awt.Color(204, 255, 204));
        btndelete.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btndelete.setForeground(new java.awt.Color(102, 153, 0));
        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        add(btndelete);
        btndelete.setBounds(450, 470, 100, 29);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 51));
        jLabel8.setText("Amount:");
        add(jLabel8);
        jLabel8.setBounds(60, 560, 72, 23);
        add(jTextField3);
        jTextField3.setBounds(150, 430, 120, 30);

        jButton1.setBackground(new java.awt.Color(204, 255, 204));
        jButton1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 102, 0));
        jButton1.setText("Read");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(570, 390, 100, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/picture/1-1024x1024.jpeg"))); // NOI18N
        add(jLabel6);
        jLabel6.setBounds(0, 0, 830, 750);
    }// </editor-fold>//GEN-END:initComponents

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        int SelectedRowIndex = jTable1.getSelectedRow();
       
      
        if (SelectedRowIndex < 0){
            
            JOptionPane.showMessageDialog(this, "Please Select a Row to Delete.");
            return;
    }
        if (SelectedRowIndex >= 0){
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        String name=model.getValueAt(SelectedRowIndex,0).toString();
        try 
        {
             String Query;
             Query="delete from market where Name='"+name+"' ";
             InsertUpdateDelete.setData(Query,"Deleted Successfully!");
       
        } catch (Exception e)
        {
            JOptionPane.showConfirmDialog(null, e);
            
        }
    
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed

        // TODO add your handling code here:
   
    String nameString=jTextField1.getText();
     String address=jTextField3.getText();
     String type=(String)TypeCombo.getSelectedItem();
     int amount=Integer.parseInt((String)jComboBox1.getSelectedItem());
     float price=Float.parseFloat(jTextField2.getText());
     
        if(address.equals(""))
            JOptionPane.showConfirmDialog(null, "Every Filed is Required!");
        else
        {
            String Query;
            Query="update market set Address='"+address+"',Category='"+type+"',amount='"+amount+"',Price='"+price+"' where Name='"+nameString+"'";
            //Query="insert into person(username,zipcode,phone number,password,address,gender,email,role)values(?,?,?,?,?,?,?,?)";
            InsertUpdateDelete.setData(Query,"Updated Successfully");
            setVisible(true);
     
        }
   
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btncreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreateActionPerformed
        // TODO add your handling code here:
     String name=jTextField1.getText();
     String address=jTextField3.getText();
     String type=(String)TypeCombo.getSelectedItem();
     int amount=Integer.parseInt((String)jComboBox1.getSelectedItem());
     String price=jTextField2.getText();
     ResultSet rs=Select.getData("select * from market where Name='"+name+"'");
     try{
     
     
        if(name.equals("")|| address.equals("") ||jTextField2.getText().equals(""))
        {JOptionPane.showConfirmDialog(null, "Every Filed is Required!");}
        else if(Validation.isName(name)==false){
               JOptionPane.showMessageDialog(this, "Name should be letters.");
            }
        else if(rs.next()){
            JOptionPane.showConfirmDialog(null, "This market already exists, please add a new one!");
        }
        else
        {
            String Query;
            Query="insert into market(Name,Address,Category,amount,Price) values('"+name+"','"+address+"','"+type+"','"+amount+"','"+price+"')";
            //Query="insert into person(username,zipcode,phone number,password,address,gender,email,role)values(?,?,?,?,?,?,?,?)";
            InsertUpdateDelete.setData(Query,"Added Successfully");
            setVisible(true);
     
        }rs.close();
     }
     catch (Exception e)
        {
            JOptionPane.showConfirmDialog(null, e);
        }
       
    }//GEN-LAST:event_btncreateActionPerformed

    private void jTable1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTable1ComponentShown
        // TODO add your handling code here:
        /*ResultSet rs=Select.getData("select * from market");
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        model.setRowCount(0);
        try {
            while(rs.next())
            {
                model.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4)});
            }
            rs.close();
                
            
        } catch (Exception e)
        {
            JOptionPane.showConfirmDialog(null, e);
            
        }*/
        
        
    }//GEN-LAST:event_jTable1ComponentShown

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int index=jTable1.getSelectedRow();
    
           if (index >= 0){
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        jTextField1.setText((String)model.getValueAt(index, 0));
               jTextField1.setEditable(false);
       
               jTextField3.setText((String)model.getValueAt(index, 1));
               
               TypeCombo.setSelectedItem((String)model.getValueAt(index,2));
               jComboBox1.setSelectedItem(String.valueOf((int)model.getValueAt(index,3)));
               jTextField2.setText(String.valueOf((float)model.getValueAt(index, 4)));
           }
           
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> TypeCombo;
    private javax.swing.JButton btncreate;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnupdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
