/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

/**
 *
 * @author chengzhishi
 */
public class DeliveryPersonJPanel extends javax.swing.JPanel {

    /**
     * Creates new form OrderJPanel
     */
    public DeliveryPersonJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DeliveryPersonAll = new javax.swing.JPanel();
        lblOrder1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        lblOrder3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        DeliveryPersonAll.setLayout(null);

        lblOrder1.setFont(new java.awt.Font("Kokonor", 3, 24)); // NOI18N
        lblOrder1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOrder1.setText("ALl Order");
        DeliveryPersonAll.add(lblOrder1);
        lblOrder1.setBounds(0, 10, 814, 42);

        jTable2.setBackground(new java.awt.Color(204, 255, 204));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Order Number", "Market Address", "Market phone number", "Customer address", "Customer phone number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        DeliveryPersonAll.add(jScrollPane2);
        jScrollPane2.setBounds(10, 50, 790, 237);

        jButton4.setBackground(new java.awt.Color(204, 255, 204));
        jButton4.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(102, 204, 0));
        jButton4.setText("Accept");
        DeliveryPersonAll.add(jButton4);
        jButton4.setBounds(630, 300, 130, 30);

        lblOrder3.setFont(new java.awt.Font("Kokonor", 3, 24)); // NOI18N
        lblOrder3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOrder3.setText("Accepted Order");
        DeliveryPersonAll.add(lblOrder3);
        lblOrder3.setBounds(0, 320, 814, 42);

        jTable4.setBackground(new java.awt.Color(204, 255, 204));
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Order Number", "Market Address", "Market phone number", "Customer address", "Customer phone number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable4);

        DeliveryPersonAll.add(jScrollPane4);
        jScrollPane4.setBounds(10, 360, 790, 237);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/picture/1-1024x1024.jpeg"))); // NOI18N
        DeliveryPersonAll.add(jLabel2);
        jLabel2.setBounds(0, 0, 800, 600);

        add(DeliveryPersonAll, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DeliveryPersonAll;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable4;
    private javax.swing.JLabel lblOrder1;
    private javax.swing.JLabel lblOrder3;
    // End of variables declaration//GEN-END:variables
}
