/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Market;
import model.markets;



/**
 *
 * @author evelyn
 */
public class MarketOwnerfood extends javax.swing.JPanel {

    /**
     * Creates new form ReFood
     */
    markets markethistory;
    public MarketOwnerfood(markets markethistory) {
        initComponents();
        this.markethistory= markethistory;
        Table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btndelete = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        txtbag = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btncreate = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        AmountComboBox = new javax.swing.JComboBox<>();
        txtprice = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/picture/order.png"))); // NOI18N

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jTable1.setBackground(new java.awt.Color(204, 255, 204));
        jTable1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(153, 255, 51));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Bag Name", "amount", "Price"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1);
        jScrollPane1.setBounds(200, 230, 430, 180);

        btndelete.setBackground(new java.awt.Color(204, 255, 204));
        btndelete.setFont(new java.awt.Font("Helvetica Neue", 3, 18)); // NOI18N
        btndelete.setForeground(new java.awt.Color(0, 204, 0));
        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        add(btndelete);
        btndelete.setBounds(550, 590, 120, 29);

        btnupdate.setBackground(new java.awt.Color(204, 255, 204));
        btnupdate.setFont(new java.awt.Font("Helvetica Neue", 3, 18)); // NOI18N
        btnupdate.setForeground(new java.awt.Color(0, 204, 51));
        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        add(btnupdate);
        btnupdate.setBounds(550, 530, 120, 29);
        add(txtbag);
        txtbag.setBounds(238, 479, 207, 23);

        jLabel2.setBackground(new java.awt.Color(51, 102, 0));
        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 0));
        jLabel2.setText("Bag Name:");
        add(jLabel2);
        jLabel2.setBounds(120, 480, 93, 23);

        btncreate.setBackground(new java.awt.Color(204, 255, 204));
        btncreate.setFont(new java.awt.Font("Helvetica Neue", 3, 18)); // NOI18N
        btncreate.setForeground(new java.awt.Color(0, 204, 0));
        btncreate.setText("Create");
        btncreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreateActionPerformed(evt);
            }
        });
        add(btncreate);
        btncreate.setBounds(550, 480, 120, 29);

        jLabel3.setBackground(new java.awt.Color(51, 102, 0));
        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 0));
        jLabel3.setText("Price:");
        add(jLabel3);
        jLabel3.setBounds(160, 600, 49, 23);

        jLabel4.setBackground(new java.awt.Color(51, 102, 0));
        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 0));
        jLabel4.setText("Amount:");
        add(jLabel4);
        jLabel4.setBounds(140, 540, 72, 23);

        AmountComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        add(AmountComboBox);
        AmountComboBox.setBounds(240, 540, 120, 23);
        add(txtprice);
        txtprice.setBounds(238, 599, 207, 23);

        jLabel6.setFont(new java.awt.Font("Kokonor", 1, 24)); // NOI18N
        jLabel6.setText("Manage food bag");
        add(jLabel6);
        jLabel6.setBounds(310, 160, 200, 42);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/picture/1-1024x1024.jpeg"))); // NOI18N
        add(jLabel5);
        jLabel5.setBounds(0, 0, 800, 680);
    }// </editor-fold>//GEN-END:initComponents

    private void btncreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreateActionPerformed
        // TODO add your handling code here:
          int amount =(int) AmountComboBox.getSelectedItem();
       
       String bag = txtbag.getText();
       Double price =Double.parseDouble(txtprice.getText());
       
       txtbag.setText("");
       AmountComboBox.setSelectedItem("");
       txtprice.setText(price.toString());
       
       JOptionPane.showMessageDialog(this,"New Bag is created!");
       
    }//GEN-LAST:event_btncreateActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    
    if(jTable1.getSelectedRowCount()==1){
        model.removeRow(jTable1.getSelectedRow());
    }else{
        if(jTable1.getRowCount()==0){
            JOptionPane.showMessageDialog(this,"Table is Empty");

        }
        else{
            JOptionPane.showMessageDialog(this,"Please select single Row for delete.");
        }
    }

    JOptionPane.showMessageDialog(this, "Bag deleted.");
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = jTable1.getSelectedRow();

        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to update.");
            return;
        }
        if (jTable1.getSelectedRowCount() == 1) {
            
            int amount = (int) AmountComboBox.getSelectedItem();

            String bag = txtbag.getText();
            Double price = Double.parseDouble(txtprice.getText());

            txtbag.setText("");
            AmountComboBox.setSelectedItem("");
            txtprice.setText(price.toString());
            
            JOptionPane.showMessageDialog(this, "Update Successfully");
        } else {
            if (jTable1.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Table is Empty");
            } else {
                JOptionPane.showMessageDialog(this, "Please select Single Row for update");
            }

        }

    }//GEN-LAST:event_btnupdateActionPerformed
public void Table(){
     DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        for(Market mar:markethistory.getHistory()){
            Object[] row = new Object[3];
            
           
            row[0] = mar.getBagname();
            row[1] = mar.getAmount();
            row[2] = mar.getPrice();
            model.addRow(row);
            
        }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AmountComboBox;
    private javax.swing.JButton btncreate;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtbag;
    private javax.swing.JTextField txtprice;
    // End of variables declaration//GEN-END:variables
}
