/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import com.sun.jdi.connect.spi.Connection;
import java.beans.Statement;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;


/**
 *
 * @author evelyn
 */
public class MarketBakeryOwner extends javax.swing.JPanel {

    /**
     * Creates new form Resaurant
     */
   
    public MarketBakeryOwner() {
        initComponents();
       
        Table();
    }
    
    
    public void Table(){
        /*DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.setRowCount(0);
        
        for(Market mar:markethistory.getHistory()){
            Object[] row = new Object[5];
            if(mar.getType()=="Bakery"){
           
            row[0] = mar.getMarketname();
            row[1] = mar.getAddress();
            row[2] = mar.getScore();
            row[3]= mar.getPrice();
            model.addRow(row);
            }
        }*/
        ResultSet rs=Select.getData("select * from market");
        DefaultTableModel model=(DefaultTableModel)jTable2.getModel();
        model.setRowCount(0);
        try {
            while(rs.next())
            {
                model.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(6)});
                
            }
            rs.close();
        
        } catch (Exception e) 
        {
            JOptionPane.showConfirmDialog(null, e);
            
        }
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
//    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MarketBakery = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        searchtxt = new javax.swing.JTextField();
        btnconfirm2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        CustomerOrder = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMarket = new javax.swing.JTextField();
        txtuser = new javax.swing.JTextField();
        txtaddress = new javax.swing.JTextField();
        txtprice = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnback = new javax.swing.JButton();
        btnconfirm = new javax.swing.JButton();
        typeComboBox = new javax.swing.JComboBox<>();
        AmountComboBox = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.CardLayout());

        MarketBakery.setLayout(null);

        jTable2.setBackground(new java.awt.Color(204, 255, 204));
        jTable2.setFont(new java.awt.Font("Helvetica Neue", 3, 12)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Address", "Ranking Score", "Price"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        MarketBakery.add(jScrollPane2);
        jScrollPane2.setBounds(120, 200, 580, 225);

        searchtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchtxtKeyReleased(evt);
            }
        });
        MarketBakery.add(searchtxt);
        searchtxt.setBounds(380, 150, 180, 23);

        btnconfirm2.setBackground(new java.awt.Color(204, 255, 204));
        btnconfirm2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnconfirm2.setForeground(new java.awt.Color(102, 204, 0));
        btnconfirm2.setText("Confirm");
        btnconfirm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconfirm2ActionPerformed(evt);
            }
        });
        MarketBakery.add(btnconfirm2);
        btnconfirm2.setBounds(610, 460, 160, 30);

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 204, 0));
        jLabel2.setText("Search:");
        MarketBakery.add(jLabel2);
        jLabel2.setBounds(300, 150, 90, 30);

        jLabel3.setFont(new java.awt.Font("Kokonor", 1, 24)); // NOI18N
        jLabel3.setText("Find a Bakery");
        MarketBakery.add(jLabel3);
        jLabel3.setBounds(350, 100, 200, 42);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/picture/1-1024x1024.jpeg"))); // NOI18N
        MarketBakery.add(jLabel14);
        jLabel14.setBounds(0, 0, 800, 630);

        add(MarketBakery, "card10");

        CustomerOrder.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 204, 0));
        jLabel4.setText("User Name:");
        CustomerOrder.add(jLabel4);
        jLabel4.setBounds(230, 210, 180, 23);

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 204, 0));
        jLabel8.setText("Amount:");
        CustomerOrder.add(jLabel8);
        jLabel8.setBounds(260, 160, 120, 23);

        jLabel5.setBackground(new java.awt.Color(204, 255, 204));
        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 204, 0));
        jLabel5.setText("Market Name:");
        CustomerOrder.add(jLabel5);
        jLabel5.setBounds(230, 110, 120, 23);

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 204, 0));
        jLabel7.setText("User Address:");
        CustomerOrder.add(jLabel7);
        jLabel7.setBounds(210, 250, 170, 30);
        CustomerOrder.add(txtMarket);
        txtMarket.setBounds(350, 110, 207, 23);
        CustomerOrder.add(txtuser);
        txtuser.setBounds(350, 210, 207, 23);
        CustomerOrder.add(txtaddress);
        txtaddress.setBounds(350, 260, 207, 23);
        CustomerOrder.add(txtprice);
        txtprice.setBounds(350, 310, 207, 23);

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 204, 0));
        jLabel9.setText("Order type:");
        CustomerOrder.add(jLabel9);
        jLabel9.setBounds(250, 360, 130, 23);

        btnback.setBackground(new java.awt.Color(204, 255, 204));
        btnback.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnback.setForeground(new java.awt.Color(102, 204, 0));
        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        CustomerOrder.add(btnback);
        btnback.setBounds(630, 30, 120, 29);

        btnconfirm.setBackground(new java.awt.Color(204, 255, 204));
        btnconfirm.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnconfirm.setForeground(new java.awt.Color(102, 204, 0));
        btnconfirm.setText("Confirm");
        btnconfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconfirmActionPerformed(evt);
            }
        });
        CustomerOrder.add(btnconfirm);
        btnconfirm.setBounds(550, 480, 120, 29);

        typeComboBox.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Delivery", "Pick-up" }));
        CustomerOrder.add(typeComboBox);
        typeComboBox.setBounds(350, 360, 130, 29);

        CustomerOrder.add(AmountComboBox);
        AmountComboBox.setBounds(350, 160, 72, 23);

        jLabel10.setFont(new java.awt.Font("Kokonor", 1, 24)); // NOI18N
        jLabel10.setText("Create a order");
        CustomerOrder.add(jLabel10);
        jLabel10.setBounds(310, 60, 200, 42);

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 204, 0));
        jLabel11.setText("Price:");
        CustomerOrder.add(jLabel11);
        jLabel11.setBounds(290, 310, 49, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/picture/1-1024x1024.jpeg"))); // NOI18N
        jLabel1.setText("jLabel1");
        CustomerOrder.add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 700);

        add(CustomerOrder, "card9");
    }// </editor-fold>//GEN-END:initComponents

    private void btnconfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconfirmActionPerformed
        // TODO add your handling code here:
         int amount =(int) AmountComboBox.getSelectedItem();  
       String type = typeComboBox.getSelectedItem().toString();
       
       /*order or = new order();
       String user = txtuser.getText();
       String address = txtuser.getText();
       //String price = amount*
       txtMarket.setText("");
       AmountComboBox.setSelectedItem("");
       txtuser.setText(user);
       txtuser.setText(address);
       txtprice.setText("");
       typeComboBox.setSelectedItem(type);
       
       Date date = new Date();
       or.setOrderDate(LocalDate.parse((CharSequence) date));
       or.setOrderNumber((int) (Math.random()*100000));
       orderhistory.addNewOrder();*/
       
       if(txtuser.getText().equals("")|| txtaddress.getText().equals("") )
            JOptionPane.showConfirmDialog(null, "Every Filed is Required!");
        else
        {
            String Query; 
            Query="insert into market(market,amount,customer,cusaddress,price,type)values(?,?,?,?,?,?)";
            InsertUpdateDelete.setData(Query,"New Order is confirmed!");
            setVisible(false);   
     
        }
        Table();

    }//GEN-LAST:event_btnconfirmActionPerformed

    private void searchtxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchtxtKeyReleased
        // TODO add your handling code here:
        /*DefaultTableModel table = (DefaultTableModel)jTable2.getModel();
        String search = searchtxt.getText();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(table);
        jTable2.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search));*/
        String name=searchtxt.getText();
        ResultSet rs=Select.getData("select * from market where Name like '%name%' ");
        DefaultTableModel model=(DefaultTableModel)jTable2.getModel();
        model.setRowCount(0);
        try {
            while(rs.next())
            {
                model.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(6)});
                
            }
            rs.close();
        
        } catch (Exception e) 
        {
            JOptionPane.showConfirmDialog(null, e);
            
        }
    }//GEN-LAST:event_searchtxtKeyReleased

    private void btnconfirm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconfirm2ActionPerformed
        // TODO add your handling code here:
         CustomerOrder.setVisible(true);
        MarketBakery.setVisible(false);
        
        int selectedRow = jTable2.getSelectedRow();
        
        if(selectedRow == -1){
            JOptionPane.showMessageDialog(this,"Please select single Row.");
        }else{
             DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
             
            String market = (String)model.getValueAt(selectedRow,0);
            
            txtMarket.setText(market);
        }
    }//GEN-LAST:event_btnconfirm2ActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
         CustomerOrder.setVisible(false);
        MarketBakery.setVisible(true);
    }//GEN-LAST:event_btnbackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AmountComboBox;
    private javax.swing.JPanel CustomerOrder;
    private javax.swing.JPanel MarketBakery;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnconfirm;
    private javax.swing.JButton btnconfirm2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField searchtxt;
    private javax.swing.JTextField txtMarket;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtuser;
    private javax.swing.JComboBox<String> typeComboBox;
    // End of variables declaration//GEN-END:variables
}
